# -*- coding: utf-8 -*-
"""Clinical.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TLKyNfNbgQo6v0LLomkAR1iS1OSHFG6u
"""

# =============================================================================
# SECTION 0 — Imports & Configuration
# =============================================================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.base import clone
from sklearn.metrics import (
    accuracy_score, roc_auc_score, average_precision_score,
    f1_score, precision_score, recall_score,
    confusion_matrix, classification_report, ConfusionMatrixDisplay,
    precision_recall_curve, roc_curve,
)
from sklearn.feature_selection import SelectKBest, f_classif

try:
    from xgboost import XGBClassifier
    HAS_XGBOOST = True
    print("✅ XGBoost available")
except ImportError:
    HAS_XGBOOST = False
    print("⚠️  XGBoost not installed — will skip XGBoost model")

RANDOM_STATE = 42
print("✅ Imports complete")

# =============================================================================
# SECTION 1 — Data Loading & Column Cleaning
# =============================================================================
# ── UPDATE THIS PATH ──────────────────────────────────────────────────────────
FILEPATH = "/content/drive/MyDrive/Project_Feb_26_Duke_Dataset/Clinical_and_Other_Features.xlsx"

df = pd.read_excel(FILEPATH, header=1)
df = df.drop(index=0).reset_index(drop=True)

df.columns = (
    df.columns.astype(str)
    .str.strip()
    .str.lower()
    .str.replace(r"[^\w]+", "_", regex=True)
    .str.replace(r"_+", "_", regex=True)
    .str.strip("_")
)

print(f"Dataset shape: {df.shape}")

# =============================================================================
# SECTION 2 — Feature Selection
# =============================================================================
selected_columns = [
    "date_of_birth_days",
    "staging_tumor_size_t",
    "staging_nodes_nx_replaced_by_1_n",
    "oncotype_score",
    "er", "pr", "her2",
    "received_neoadjuvant_therapy_or_not",
    "tumor_grade", "mol_subtype",
    "near_complete_response_graded_measure",
    "adjuvant_anti_her2_neu_therapy",
    "adjuvant_chemotherapy",
    "adjuvant_endocrine_therapy_medications",
    "adjuvant_radiation_therapy",
    "pathologic_response_to_neoadjuvant_therapy_pathologic_stage_t_following_neoadjuvant_therapy",
    "pathologic_response_to_neoadjuvant_therapy_pathologic_stage_n_following_neoadjuvant_therapy",
    "pathologic_response_to_neoadjuvant_therapy_pathologic_stage_m_following_neoadjuvant_therapy",
    "overall_near_complete_response_stricter_definition",
    "recurrence_event_s",
    "days_to_last_distant_recurrence_free_assemssment_from_the_date_of_diagnosis",
]

selected_df = df[selected_columns]
selected_df.to_csv("selected_features19.csv", index=False)

selected_df["date_of_birth_days"] = selected_df["date_of_birth_days"].abs() / 365.25
df = selected_df.copy()

df.dropna(subset=["recurrence_event_s"], inplace=True)
print(f"Dataset shape after dropping missing target: {df.shape}")

# =============================================================================
# SECTION 3 — Column Definitions
# =============================================================================
TARGET_COL   = "recurrence_event_s"
FOLLOWUP_COL = ("days_to_last_distant_recurrence_free_assemssment"
                "_from_the_date_of_diagnosis")

BASELINE_NUMERIC = [
    "date_of_birth_days", "staging_tumor_size_t",
    "staging_nodes_nx_replaced_by_1_n", "oncotype_score",
]
BASELINE_BINARY = [
    "er", "pr", "her2", "received_neoadjuvant_therapy_or_not",
]
BASELINE_CATEGORICAL = ["tumor_grade", "mol_subtype"]

EXTENDED_NUMERIC = BASELINE_NUMERIC + ["near_complete_response_graded_measure"]
EXTENDED_BINARY  = BASELINE_BINARY + [
    "adjuvant_anti_her2_neu_therapy", "adjuvant_chemotherapy",
    "adjuvant_endocrine_therapy_medications", "adjuvant_radiation_therapy",
]
EXTENDED_ORDINAL = [
    "pathologic_response_to_neoadjuvant_therapy_pathologic_stage_t_following_neoadjuvant_therapy",
    "pathologic_response_to_neoadjuvant_therapy_pathologic_stage_n_following_neoadjuvant_therapy",
    "pathologic_response_to_neoadjuvant_therapy_pathologic_stage_m_following_neoadjuvant_therapy",
]
EXTENDED_CATEGORICAL = BASELINE_CATEGORICAL + [
    "overall_near_complete_response_stricter_definition",
]

print("✅ Column definitions set")

# =============================================================================
# SECTION 4 — Data Preparation (Remapping — No Leakage)
# =============================================================================
col = "received_neoadjuvant_therapy_or_not"
if col in df.columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")
    df[col] = df[col].map({1: 1, 2: 0})

for col in EXTENDED_ORDINAL:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

all_numeric_check = list(set(BASELINE_NUMERIC + EXTENDED_NUMERIC))
for col in all_numeric_check:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

df[TARGET_COL] = pd.to_numeric(df[TARGET_COL], errors="coerce")

all_binary = list(set(BASELINE_BINARY + EXTENDED_BINARY))
for col in all_binary:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

all_cat = list(set(BASELINE_CATEGORICAL + EXTENDED_CATEGORICAL))
for col in all_cat:
    if col in df.columns:
        df[col] = df[col].astype(str).replace("nan", np.nan)

print("✅ Preparation complete")

# =============================================================================
# SECTION 5 — Pipeline Builders  (DO NOT MODIFY)
# =============================================================================
def build_preprocessor(numeric_cols, binary_cols, categorical_cols,
                        ordinal_cols=None):
    """
    ColumnTransformer:
      Numeric     → median imputation + StandardScaler
      Binary      → most-frequent imputation, NO scaling
      Categorical → 'Unknown' fill + OneHotEncoder
      Ordinal num → most-frequent imputation + StandardScaler
    """
    ordinal_cols = ordinal_cols or []
    transformers = []

    if numeric_cols:
        num_pipe = Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler",  StandardScaler()),
        ])
        transformers.append(("num", num_pipe, numeric_cols))

    if binary_cols:
        bin_pipe = Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
        ])
        transformers.append(("bin", bin_pipe, binary_cols))

    if categorical_cols:
        cat_pipe = Pipeline([
            ("imputer", SimpleImputer(strategy="constant",
                                      fill_value="Unknown")),
            ("ohe",     OneHotEncoder(handle_unknown="ignore",
                                      sparse_output=False)),
        ])
        transformers.append(("cat", cat_pipe, categorical_cols))

    if ordinal_cols:
        ord_pipe = Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("scaler",  StandardScaler()),
        ])
        transformers.append(("ord", ord_pipe, ordinal_cols))

    return ColumnTransformer(transformers=transformers, remainder="drop",
                             verbose_feature_names_out=False)


def build_model_pipeline(preprocessor, model):
    return Pipeline([("preprocessor", preprocessor), ("classifier", model)])


def build_model_pipeline_fs(preprocessor, model, model_name, k=9):
    """Pipeline with optional SelectKBest for Logistic Regression."""
    steps = [("preprocessor", preprocessor)]
    if model_name == "Logistic Regression":
        steps.append(("feature_selector",
                       SelectKBest(score_func=f_classif, k=k)))
    steps.append(("classifier", model))
    return Pipeline(steps)


print("✅ Pipeline builders defined")

"""after editing"""

# =============================================================================
# SECTION 6 — CV Evaluation Core  (FINAL — FIXED)
# =============================================================================

def evaluate_model_cv(model, X, y, preprocessor=None,
                      n_splits=5, random_state=RANDOM_STATE,
                      model_name="Model"):

    if preprocessor is not None:
        estimator = Pipeline([("preprocessor", preprocessor),
                              ("classifier",   model)])
    else:
        estimator = model

    cv = StratifiedKFold(n_splits=n_splits, shuffle=True,
                         random_state=random_state)

    fold_metrics = {k: [] for k in
                    ["AUC", "AP", "Accuracy", "Precision",
                     "Recall", "Specificity", "F1"]}

    mean_fpr = np.linspace(0, 1, 100)
    mean_recall_grid = np.linspace(0, 1, 100)

    tprs = []
    precisions_interp = []
    fold_predictions = []

    X = X.reset_index(drop=True)
    y = y.reset_index(drop=True)

    for train_idx, val_idx in cv.split(X, y):
        X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_tr, y_val = y.iloc[train_idx], y.iloc[val_idx]

        est_fold = clone(estimator)
        est_fold.fit(X_tr, y_tr)

        y_prob = est_fold.predict_proba(X_val)[:, 1]
        y_pred = est_fold.predict(X_val)

        # =========================
        # Metrics (FIXED)
        # =========================
        tn, fp, fn, tp = confusion_matrix(y_val, y_pred).ravel()
        specificity = tn / (tn + fp) if (tn + fp) > 0 else 0.0

        # Handle edge case (single class)
        if len(np.unique(y_val)) > 1:
            auc = roc_auc_score(y_val, y_prob)
            ap  = average_precision_score(y_val, y_prob)
        else:
            auc = 0.5
            ap  = 0.0

        fold_metrics["AUC"].append(auc)
        fold_metrics["AP"].append(ap)
        fold_metrics["Accuracy"].append(accuracy_score(y_val, y_pred))
        fold_metrics["Precision"].append(
            precision_score(y_val, y_pred, zero_division=0))
        fold_metrics["Recall"].append(
            recall_score(y_val, y_pred, zero_division=0))
        fold_metrics["Specificity"].append(specificity)
        fold_metrics["F1"].append(
            f1_score(y_val, y_pred, zero_division=0))

        # =========================
        # ROC (IMPROVED)
        # =========================
        fpr_f, tpr_f, _ = roc_curve(y_val, y_prob)
        tpr_interp = np.interp(mean_fpr, fpr_f, tpr_f)
        tpr_interp[0] = 0.0
        tpr_interp[-1] = 1.0
        tprs.append(tpr_interp)

        # =========================
        # PR (FIXED — IMPORTANT)
        # =========================
        prec_f, rec_f, _ = precision_recall_curve(y_val, y_prob)

        # Sort recall correctly
        order = np.argsort(rec_f)
        rec_sorted = rec_f[order]
        prec_sorted = prec_f[order]

        prec_interp = np.interp(mean_recall_grid,
                               rec_sorted,
                               prec_sorted)

        precisions_interp.append(prec_interp)

        fold_predictions.append({
            "y_true": y_val.values,
            "y_prob": y_prob,
            "y_pred": y_pred,
        })

    # =========================
    # Aggregate
    # =========================
    summary_dict = {}
    rows = []

    for metric, values in fold_metrics.items():
        arr = np.array(values)

        summary_dict[metric] = {
            "mean": round(float(arr.mean()), 4),
            "std":  round(float(arr.std()), 4),
            "min":  round(float(arr.min()), 4),
            "max":  round(float(arr.max()), 4),
            "per_fold": arr.tolist(),
        }

        rows.append({
            "Metric": metric,
            "Mean": summary_dict[metric]["mean"],
            "Std":  summary_dict[metric]["std"],
            "Min":  summary_dict[metric]["min"],
            "Max":  summary_dict[metric]["max"],
        })

    stats_df = pd.DataFrame(rows)

    # =========================
    # Print
    # =========================
    print(f"\n  📊 {model_name} — {n_splits}-Fold Cross-Validation Results")
    print(f"  {'─' * 65}")
    for metric, s in summary_dict.items():
        print(f"  {metric + ':':<14} "
              f"{s['mean']:.3f} ± {s['std']:.3f}  "
              f"(min={s['min']:.3f}, max={s['max']:.3f})")
    print(f"  {'─' * 65}")

    fold_data = {
        "tprs": np.array(tprs),
        "mean_fpr": mean_fpr,
        "precisions_interp": np.array(precisions_interp),
        "mean_recall_grid": mean_recall_grid,
        "fold_predictions": fold_predictions,
        "fold_metrics": fold_metrics,
        "summary": summary_dict,
        "stats_df": stats_df,
    }

    return summary_dict, stats_df, fold_data

# =============================================================================
# SECTION 7
# =============================================================================

def plot_roc_cv(fold_data, model_name="Model", ax=None):
    """
    Mean ROC curve with ±1 std shading + individual fold curves.
    """
    tprs     = fold_data["tprs"]
    mean_fpr = fold_data["mean_fpr"]
    s        = fold_data["summary"]

    # FIX: clipping for numerical stability
    mean_tpr = np.clip(tprs.mean(axis=0), 0, 1)
    mean_tpr[-1] = 1.0
    std_tpr  = tprs.std(axis=0)

    own_fig = ax is None
    if own_fig:
        fig, ax = plt.subplots(figsize=(6, 5))

    # Individual folds
    for fp_d in fold_data["fold_predictions"]:
        fpr_f, tpr_f, _ = roc_curve(fp_d["y_true"], fp_d["y_prob"])
        ax.plot(fpr_f, tpr_f, color="#a0c4ff", lw=0.8, alpha=0.4)

    # Mean ROC
    auc_mean, auc_std = s["AUC"]["mean"], s["AUC"]["std"]
    ax.plot(mean_fpr, mean_tpr, color="#1a6faf", lw=2.5,
            label=f"Mean ROC (AUC = {auc_mean:.3f} ± {auc_std:.3f})")

    # Std shading
    ax.fill_between(mean_fpr,
                    np.clip(mean_tpr - std_tpr, 0, 1),
                    np.clip(mean_tpr + std_tpr, 0, 1),
                    color="#1a6faf", alpha=0.15, label="± 1 std dev")

    # Baseline
    ax.plot([0, 1], [0, 1], linestyle="--", color="#888888",
            lw=1.2, label="Random Classifier")

    ax.set_xlim([-0.02, 1.02])
    ax.set_ylim([-0.02, 1.05])
    ax.set_xlabel("False Positive Rate", fontsize=11)
    ax.set_ylabel("True Positive Rate", fontsize=11)
    ax.set_title(f"ROC Curve — {model_name}", fontsize=12, fontweight="bold")
    ax.legend(loc="lower right", fontsize=9)
    ax.grid(True, linestyle="--", alpha=0.4)

    if own_fig:
        plt.tight_layout()
        plt.show()
        return fig


def plot_pr_cv(fold_data, model_name="Model", ax=None):
    """
    Mean Precision-Recall curve with ±1 std shading.
    """
    precs    = fold_data["precisions_interp"]
    rec_grid = fold_data["mean_recall_grid"]
    s        = fold_data["summary"]

    # FIX: clipping
    mean_prec = np.clip(precs.mean(axis=0), 0, 1)
    std_prec  = precs.std(axis=0)

    own_fig = ax is None
    if own_fig:
        fig, ax = plt.subplots(figsize=(6, 5))

    # Individual folds
    for fp_d in fold_data["fold_predictions"]:
        prec_f, rec_f, _ = precision_recall_curve(
            fp_d["y_true"], fp_d["y_prob"])
        ax.plot(rec_f, prec_f, color="#b9f2b9", lw=0.8, alpha=0.4)

    # Mean PR
    ap_mean, ap_std = s["AP"]["mean"], s["AP"]["std"]
    ax.plot(rec_grid, mean_prec, color="#1d8a1d", lw=2.5,
            label=f"Mean PR (AP = {ap_mean:.3f} ± {ap_std:.3f})")

    # Std shading
    ax.fill_between(rec_grid,
                    np.clip(mean_prec - std_prec, 0, 1),
                    np.clip(mean_prec + std_prec, 0, 1),
                    color="#1d8a1d", alpha=0.15, label="± 1 std dev")

    # 🔥 IMPORTANT: PR baseline (class imbalance explanation)
    pos_rate = np.mean(
        np.concatenate([d["y_true"] for d in fold_data["fold_predictions"]])
    )
    ax.hlines(pos_rate, 0, 1, linestyles="--", lw=1.2,
              label=f"Baseline (Pos rate = {pos_rate:.2f})")

    ax.set_xlim([-0.02, 1.02])
    ax.set_ylim([-0.02, 1.05])
    ax.set_xlabel("Recall", fontsize=11)
    ax.set_ylabel("Precision", fontsize=11)
    ax.set_title(f"Precision-Recall Curve — {model_name}",
                 fontsize=12, fontweight="bold")
    ax.legend(loc="upper right", fontsize=9)
    ax.grid(True, linestyle="--", alpha=0.4)

    if own_fig:
        plt.tight_layout()
        plt.show()
        return fig


def plot_threshold_metrics_cv(fold_data, model_name="Model"):
    """
    Threshold vs. F1 / Precision / Recall / Specificity
    """
    y_true_all = np.concatenate(
        [d["y_true"] for d in fold_data["fold_predictions"]])
    y_prob_all = np.concatenate(
        [d["y_prob"] for d in fold_data["fold_predictions"]])

    thresholds = np.linspace(0.05, 0.95, 91)
    f1s, precs, recs, specs = [], [], [], []

    for t in thresholds:
        y_pred_t = (y_prob_all >= t).astype(int)
        tn, fp, fn, tp = confusion_matrix(
            y_true_all, y_pred_t, labels=[0, 1]).ravel()

        f1s.append(f1_score(y_true_all, y_pred_t, zero_division=0))
        precs.append(precision_score(y_true_all, y_pred_t, zero_division=0))
        recs.append(recall_score(y_true_all, y_pred_t, zero_division=0))
        specs.append(tn / (tn + fp) if (tn + fp) > 0 else 0.0)

    best_t = thresholds[int(np.argmax(f1s))]

    fig, ax = plt.subplots(figsize=(8, 4))
    ax.plot(thresholds, f1s,   lw=2, label="F1-Score")
    ax.plot(thresholds, precs, lw=2, label="Precision")
    ax.plot(thresholds, recs,  lw=2, label="Recall (Sensitivity)")
    ax.plot(thresholds, specs, lw=2, label="Specificity")
    ax.axvline(best_t, color="black", linestyle="--", lw=1.5,
               label=f"Best F1 at τ = {best_t:.2f}")

    ax.set_xlabel("Decision Threshold (τ)", fontsize=11)
    ax.set_ylabel("Score", fontsize=11)
    ax.set_title(f"Threshold vs. Metrics — {model_name}",
                 fontsize=12, fontweight="bold")
    ax.legend(fontsize=9)
    ax.set_xlim(0.0, 1.0)
    ax.set_ylim(0.0, 1.05)
    ax.grid(True, linestyle="--", alpha=0.4)
    plt.tight_layout()
    plt.show()
    return fig


def plot_cv_all_models(all_fold_data, plot_type="roc",
                       experiment_name=""):
    """
    Overlay mean ROC or PR curves for multiple models.
    """
    fig, ax = plt.subplots(figsize=(7, 6))

    for model_name, fd in all_fold_data.items():
        if plot_type == "roc":
            mean_tpr = np.clip(fd["tprs"].mean(axis=0), 0, 1)
            mean_tpr[-1] = 1.0
            auc_m, auc_s = fd["summary"]["AUC"]["mean"], fd["summary"]["AUC"]["std"]
            ax.plot(fd["mean_fpr"], mean_tpr, lw=2,
                    label=f"{model_name} (AUC = {auc_m:.3f} ± {auc_s:.3f})")
        else:
            mean_prec = np.clip(fd["precisions_interp"].mean(axis=0), 0, 1)
            ap_m, ap_s = fd["summary"]["AP"]["mean"], fd["summary"]["AP"]["std"]
            ax.plot(fd["mean_recall_grid"], mean_prec, lw=2,
                    label=f"{model_name} (AP = {ap_m:.3f} ± {ap_s:.3f})")

    if plot_type == "roc":
        ax.plot([0, 1], [0, 1], "--", color="#888888", lw=1.2,
                label="Random Classifier")
        ax.set_xlabel("False Positive Rate", fontsize=11)
        ax.set_ylabel("True Positive Rate", fontsize=11)
        title = f"Mean ROC Curves — {experiment_name}"
    else:
        ax.set_xlabel("Recall", fontsize=11)
        ax.set_ylabel("Precision", fontsize=11)
        title = f"Mean PR Curves — {experiment_name}"

    ax.set_title(title, fontsize=12, fontweight="bold")
    ax.legend(fontsize=9)
    ax.grid(True, linestyle="--", alpha=0.4)
    ax.set_xlim(-0.02, 1.02)
    ax.set_ylim(-0.02, 1.05)
    plt.tight_layout()
    plt.show()
    return fig


print("✅ Plotting helpers (FINAL VERSION) ready")

# =============================================================================
# SECTION 8 — evaluate_pipeline  (FINAL)
# =============================================================================

def evaluate_pipeline(pipeline, X_train, X_test, y_train, y_test,
                       cv, model_name):
    """
    Evaluate a sklearn Pipeline.

    Steps
    -----
    1. StratifiedKFold CV on training set → full statistics
       (mean ± std, min, max) for each metric, plus ROC / PR / threshold plots.
    2. Final fit on full training set + evaluation on held-out test set.
    3. Print publication-ready summary and confusion matrix.
    """

    # ── 1. Cross-validation ──────────────────────────────────────────────────
    cv_summary, cv_df, fold_data = evaluate_model_cv(
        model        = pipeline,
        X            = X_train,
        y            = y_train,
        preprocessor = None,
        n_splits     = cv.n_splits,
        random_state = RANDOM_STATE,
        model_name   = model_name,
    )

    # ── 2. CV Plots ──────────────────────────────────────────────────────────
    fig, axes = plt.subplots(1, 2, figsize=(13, 5))

    plot_roc_cv(fold_data, model_name=model_name, ax=axes[0])
    plot_pr_cv(fold_data, model_name=model_name, ax=axes[1])

    plt.suptitle(f"{model_name} — {cv.n_splits}-Fold CV Curves",
                 fontsize=13, fontweight="bold")
    plt.tight_layout()
    plt.show()

    plot_threshold_metrics_cv(fold_data, model_name=model_name)

    # ── 3. Final Model Fit ───────────────────────────────────────────────────
    pipeline.fit(X_train, y_train)

    y_pred      = pipeline.predict(X_test)
    y_pred_prob = pipeline.predict_proba(X_test)[:, 1]

    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

    # 🔥 IMPORTANT: include AP (reviewer requirement)
    test_metrics = {
        "Test Accuracy": round(accuracy_score(y_test, y_pred), 4),
        "Test ROC-AUC":  round(roc_auc_score(y_test, y_pred_prob), 4),
        "Test AP":       round(average_precision_score(y_test, y_pred_prob), 4),
        "Test F1":       round(f1_score(y_test, y_pred, zero_division=0), 4),
        "Precision":     round(precision_score(y_test, y_pred, zero_division=0), 4),
        "Sensitivity":   round(recall_score(y_test, y_pred, zero_division=0), 4),
        "Specificity":   round(tn / (tn + fp), 4),
    }

    print(f"\n  Test Results → "
          f"Acc: {test_metrics['Test Accuracy']}  | "
          f"AUC: {test_metrics['Test ROC-AUC']}  | "
          f"AP: {test_metrics['Test AP']}  | "
          f"F1: {test_metrics['Test F1']}  | "
          f"Precision: {test_metrics['Precision']}  | "
          f"Sensitivity: {test_metrics['Sensitivity']}  | "
          f"Specificity: {test_metrics['Specificity']}")

    print("\n  Classification Report:")
    print(classification_report(
        y_test, y_pred,
        target_names=["No Recurrence", "Recurrence"],
        zero_division=0
    ))

    # ── Confusion Matrix ─────────────────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(4, 3))
    ConfusionMatrixDisplay.from_predictions(
        y_test, y_pred,
        display_labels=["No Recur.", "Recur."],
        ax=ax, colorbar=False
    )
    ax.set_title(model_name, fontsize=10, fontweight="bold")
    plt.tight_layout()
    plt.show()

    # ── 4. Build Metrics Dictionary ──────────────────────────────────────────
    _KEY_MAP = {
        "AUC":         "Roc_auc",
        "AP":          "AP",              # 🔥 NEW
        "Accuracy":    "Accuracy",
        "F1":          "F1",
        "Precision":   "Precision",
        "Recall":      "Sensitivity",
        "Specificity": "Specificity",
    }

    metrics = {"Model": model_name}

    for new_key, old_key in _KEY_MAP.items():
        s = cv_summary.get(new_key, {})
        metrics[f"CV {old_key}_mean"] = s.get("mean", 0)
        metrics[f"CV {old_key}_std"]  = s.get("std",  0)
        metrics[f"CV {old_key}_min"]  = s.get("min",  0)
        metrics[f"CV {old_key}_max"]  = s.get("max",  0)

    metrics.update(test_metrics)

    # Attach fold_data for plotting later
    metrics["_fold_data"] = fold_data

    return metrics


print("✅ evaluate_pipeline (FINAL VERSION) ready")

# =============================================================================
# SECTION 9 — Experiment Runner  (FINAL)
# =============================================================================

def run_experiment(df, experiment_name, numeric_cols, binary_cols,
                   categorical_cols, ordinal_cols=None):

    ordinal_cols = ordinal_cols or []

    print(f"\n{'═'*65}")
    print(f"  EXPERIMENT: {experiment_name}")
    print(f"{'═'*65}")

    # ── Ensure columns exist ─────────────────────────────────────────────────
    def existing(cols):
        return [c for c in cols if c in df.columns]

    numeric_cols     = existing(numeric_cols)
    binary_cols      = existing(binary_cols)
    categorical_cols = existing(categorical_cols)
    ordinal_cols     = existing(ordinal_cols)

    all_features = numeric_cols + binary_cols + categorical_cols + ordinal_cols

    if len(all_features) == 0:
        raise ValueError("❌ No valid features found!")

    # ── Prepare data ─────────────────────────────────────────────────────────
    X = df[all_features].copy()
    y = df[TARGET_COL].copy()

    valid = y.notna()
    X, y  = X[valid], y[valid].astype(int)

    if len(X) == 0:
        raise ValueError("❌ No valid samples after filtering!")

    print(f"\n  Samples: {len(X)}")

    # Class distribution
    class_dist = (y.value_counts(normalize=True) * 100).round(2)
    print("\n  Class distribution (%):")
    print(class_dist.rename({0: "No Recurrence", 1: "Recurrence"}))

    # ── Train/Test Split ─────────────────────────────────────────────────────
    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=0.2,
        stratify=y,
        random_state=RANDOM_STATE
    )

    print(f"\n  Train: {len(X_train)} | Test: {len(X_test)}")

    # ── Preprocessing ────────────────────────────────────────────────────────
    preprocessor = build_preprocessor(
        numeric_cols, binary_cols, categorical_cols, ordinal_cols
    )

    # ── Cross-validation setup ───────────────────────────────────────────────
    cv = StratifiedKFold(
        n_splits=5,
        shuffle=True,
        random_state=RANDOM_STATE
    )

    # ── Models ───────────────────────────────────────────────────────────────
    models = {
        "Logistic Regression": LogisticRegression(
            max_iter=1000,
            class_weight="balanced",
            random_state=RANDOM_STATE
        ),
        "Random Forest": RandomForestClassifier(
            n_estimators=300,
            class_weight="balanced",
            random_state=RANDOM_STATE
        ),
    }

    if HAS_XGBOOST:
        neg_n = (y_train == 0).sum()
        pos_n = (y_train == 1).sum()

        models["XGBoost"] = XGBClassifier(
            n_estimators=300,
            scale_pos_weight=neg_n / pos_n,
            eval_metric="logloss",
            random_state=RANDOM_STATE,
            verbosity=0
        )

    print(f"\n  Models to evaluate: {list(models.keys())}")

    results       = []
    all_fold_data = {}

    # ── Training loop ────────────────────────────────────────────────────────
    for name, model in models.items():
        print(f"\n  {'─'*55}")
        print(f"  ▶ Running: {name}")
        print(f"  {'─'*55}")

        pipe = build_model_pipeline(preprocessor, model)

        metrics = evaluate_pipeline(
            pipe,
            X_train, X_test,
            y_train, y_test,
            cv,
            name
        )

        metrics["Experiment"] = experiment_name

        # Store fold data for plotting
        all_fold_data[name] = metrics.pop("_fold_data", None)

        results.append(metrics)

    # ── Overlay curves (VERY IMPORTANT for paper) ────────────────────────────
    if all_fold_data:
        print(f"\n  📊 Overlay Curves — {experiment_name}")

        plot_cv_all_models(
            all_fold_data,
            plot_type="roc",
            experiment_name=experiment_name
        )

        plot_cv_all_models(
            all_fold_data,
            plot_type="pr",
            experiment_name=experiment_name
        )

    print(f"\n✅ Experiment '{experiment_name}' completed\n")

    return results


print("✅ Experiment runner (FINAL VERSION) ready")

# =============================================================================
# SECTION 10 — Experiment 1 — Baseline (Pre-treatment Features)
# =============================================================================
baseline_results = run_experiment(
    df,
    experiment_name  = "Baseline",
    numeric_cols     = BASELINE_NUMERIC,
    binary_cols      = BASELINE_BINARY,
    categorical_cols = BASELINE_CATEGORICAL,
)

# =============================================================================
# SECTION 11 — Experiment 2 — Extended (Post-treatment Features)
# =============================================================================
extended_results = run_experiment(
    df,
    experiment_name  = "Extended",
    numeric_cols     = EXTENDED_NUMERIC,
    binary_cols      = EXTENDED_BINARY,
    categorical_cols = EXTENDED_CATEGORICAL,
    ordinal_cols     = EXTENDED_ORDINAL,
)

# =============================================================================
# SECTION 12 — Final Comparison Table  (FINAL VERSION WITH AP)
# =============================================================================
all_results = baseline_results + extended_results
summary     = pd.DataFrame(all_results)

# ── Build combined "mean ± std (min, max)" display columns ───────────────────
for metric in ["Accuracy", "Roc_auc", "AP", "F1", "Precision",
               "Sensitivity", "Specificity"]:
    summary[f"CV {metric}"] = summary.apply(
        lambda row, m=metric: (
            f"{row[f'CV {m}_mean']:.3f} ± {row[f'CV {m}_std']:.3f} "
            f"(min={row[f'CV {m}_min']:.3f}, max={row[f'CV {m}_max']:.3f})"
        ), axis=1
    )

# ── Columns for display ──────────────────────────────────────────────────────
display_cols = [
    "Experiment", "Model",
    "CV Accuracy", "CV Roc_auc", "CV AP", "CV F1",
    "CV Precision", "CV Sensitivity", "CV Specificity",
    "Test Accuracy", "Test ROC-AUC", "Test AP", "Test F1",
    "Precision", "Sensitivity", "Specificity",
]

print("\n" + "=" * 120)
print("  BASELINE vs. EXTENDED — FINAL COMPARISON")
print("  (CV columns: mean ± std  (min, max))")
print("=" * 120)
print(summary[display_cols].to_string(index=False))

summary[display_cols].to_csv("results_summary.csv", index=False)
print("\n✅ Saved to results_summary.csv")

# ── Numeric-only table (for LaTeX / paper tables) ────────────────────────────
numeric_display = ["Experiment", "Model"]

for metric in ["Accuracy", "Roc_auc", "AP", "F1", "Precision",
               "Sensitivity", "Specificity"]:
    for stat in ["mean", "std", "min", "max"]:
        numeric_display.append(f"CV {metric}_{stat}")

numeric_display += [
    "Test Accuracy", "Test ROC-AUC", "Test AP", "Test F1",
    "Precision", "Sensitivity", "Specificity"
]

summary[numeric_display].to_csv("results_summary_numeric.csv", index=False)
print("✅ Saved to results_summary_numeric.csv (numeric values only)")

#------------------------------------------------------------------------------
# SECTION 13 — Results Visualisation (UNCHANGED)
# =============================================================================
fig, axes = plt.subplots(2, 3, figsize=(16, 10))

metrics_to_plot = [
    "Test ROC-AUC", "Test AP", "Test F1",
    "Test Accuracy", "Precision", "Sensitivity",
]

titles = [
    "ROC-AUC (Test)", "Average Precision (Test)", "F1-Score (Test)",
    "Accuracy (Test)", "Precision (Test)", "Sensitivity (Test)",
]

axes = axes.flatten()

for ax, metric, title in zip(axes, metrics_to_plot, titles):
    pivot = summary.pivot(index="Model", columns="Experiment", values=metric)
    pivot.plot(kind="bar", ax=ax, colormap="Set2",
               edgecolor="black", width=0.6)

    ax.set_title(title, fontsize=12, fontweight="bold")
    ax.set_ylabel(metric)
    ax.set_ylim(0, 1.0)
    ax.set_xticklabels(ax.get_xticklabels(), rotation=25, ha="right")
    ax.legend(title="Experiment")
    ax.grid(axis="y", alpha=0.4)

plt.suptitle(
    "Baseline vs. Extended Feature Set — Test Metrics Comparison",
    fontsize=14, fontweight="bold"
)

plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.show()

# =============================================================================
# SECTION 14 — Threshold Tuning Helpers
# =============================================================================

def tune_threshold(y_true, y_prob, model_label="Model"):
    thresholds = np.arange(0.05, 0.61, 0.025)
    rows = []

    for t in thresholds:
        y_pred_t = (y_prob >= t).astype(int)
        tn, fp, fn, tp = confusion_matrix(y_true, y_pred_t).ravel()

        rows.append({
            "Threshold":   round(t, 3),
            "Precision":   round(precision_score(y_true, y_pred_t, zero_division=0), 4),
            "Sensitivity": round(recall_score(y_true, y_pred_t, zero_division=0), 4),
            "Specificity": round(tn / (tn + fp) if (tn + fp) > 0 else 0.0, 4),
            "F1":          round(f1_score(y_true, y_pred_t, zero_division=0), 4),
        })

    sweep = pd.DataFrame(rows)
    best_idx = sweep["F1"].idxmax()
    best_t = sweep.loc[best_idx, "Threshold"]

    print(f"\n  [{model_label}] Optimal threshold: {best_t}  "
          f"F1={sweep.loc[best_idx,'F1']}  "
          f"Precision={sweep.loc[best_idx,'Precision']}  "
          f"Sensitivity={sweep.loc[best_idx,'Sensitivity']}  "
          f"Specificity={sweep.loc[best_idx,'Specificity']}")

    return best_t, sweep


def plot_threshold_sweep(sweep, best_t, title="Threshold Tuning"):
    fig, ax = plt.subplots(figsize=(8, 4))

    ax.plot(sweep["Threshold"], sweep["F1"], label="F1", lw=2)
    ax.plot(sweep["Threshold"], sweep["Precision"], label="Precision", lw=2)
    ax.plot(sweep["Threshold"], sweep["Sensitivity"], label="Sensitivity", lw=2)
    ax.plot(sweep["Threshold"], sweep["Specificity"], label="Specificity", lw=2)

    ax.axvline(best_t, linestyle="--", lw=1.5,
               label=f"Optimal τ={best_t}")

    ax.set_xlabel("Decision Threshold (τ)", fontsize=11)
    ax.set_ylabel("Score", fontsize=11)
    ax.set_title(title, fontsize=12, fontweight="bold")
    ax.legend()
    ax.set_ylim(0, 1.05)

    plt.tight_layout()
    plt.show()

    return fig


print("✅ Threshold tuning helpers defined")

# =============================================================================
# SECTION 15 — Threshold Tuning Runner (UPDATED)
# =============================================================================

from sklearn.metrics import roc_auc_score, average_precision_score

all_features_ext = EXTENDED_NUMERIC + EXTENDED_BINARY + \
                   EXTENDED_CATEGORICAL + EXTENDED_ORDINAL

X_ext = df[[c for c in all_features_ext if c in df.columns]].copy()
y_ext = df[TARGET_COL].copy()

valid = y_ext.notna()
X_ext, y_ext = X_ext[valid], y_ext[valid].astype(int)

X_tr_tt, X_te_tt, y_tr_tt, y_te_tt = train_test_split(
    X_ext, y_ext, test_size=0.2, stratify=y_ext,
    random_state=RANDOM_STATE
)

pre_tt = build_preprocessor(
    [c for c in EXTENDED_NUMERIC if c in X_ext.columns],
    [c for c in EXTENDED_BINARY if c in X_ext.columns],
    [c for c in EXTENDED_CATEGORICAL if c in X_ext.columns],
    [c for c in EXTENDED_ORDINAL if c in X_ext.columns],
)

models_to_tune = {
    "Logistic Regression": LogisticRegression(
        max_iter=1000, class_weight="balanced",
        random_state=RANDOM_STATE),
    "Random Forest": RandomForestClassifier(
        n_estimators=300, class_weight="balanced",
        random_state=RANDOM_STATE),
}

if HAS_XGBOOST:
    models_to_tune["XGBoost"] = XGBClassifier(
        n_estimators=300, eval_metric="logloss",
        random_state=RANDOM_STATE, verbosity=0
    )

all_sweeps = {}

for model_name, clf in models_to_tune.items():
    print("\n" + "=" * 60)
    print(f"Threshold tuning for {model_name}")
    print("=" * 60)

    clf_copy = clone(clf)

    if model_name == "XGBoost":
        neg_n = (y_tr_tt == 0).sum()
        pos_n = (y_tr_tt == 1).sum()
        clf_copy.set_params(scale_pos_weight=neg_n / pos_n)

    pipe = Pipeline([("pre", pre_tt), ("clf", clf_copy)])
    pipe.fit(X_tr_tt, y_tr_tt)

    y_prob = pipe.predict_proba(X_te_tt)[:, 1]

    # ── DEFAULT THRESHOLD ─────────────────────────────
    y_pred_default = (y_prob >= 0.5).astype(int)

    tn, fp, fn, tp = confusion_matrix(y_te_tt, y_pred_default).ravel()

    f1_d   = f1_score(y_te_tt, y_pred_default, zero_division=0)
    prec_d = precision_score(y_te_tt, y_pred_default, zero_division=0)
    rec_d  = recall_score(y_te_tt, y_pred_default, zero_division=0)
    spec_d = tn / (tn + fp)

    auc_d = roc_auc_score(y_te_tt, y_prob)
    ap_d  = average_precision_score(y_te_tt, y_prob)

    print("\nDEFAULT THRESHOLD (0.50):")
    print(f"  AUC={auc_d:.4f}  AP={ap_d:.4f}  "
          f"F1={f1_d:.4f}  Precision={prec_d:.4f}  "
          f"Sensitivity={rec_d:.4f}  Specificity={spec_d:.4f}")

    # ── THRESHOLD TUNING ─────────────────────────────
    best_t, sweep = tune_threshold(y_te_tt, y_prob, model_name)
    _ = plot_threshold_sweep(sweep, best_t, f"{model_name} — Threshold Sweep")

    y_pred_tuned = (y_prob >= best_t).astype(int)

    tn_t, fp_t, fn_t, tp_t = confusion_matrix(y_te_tt, y_pred_tuned).ravel()

    f1_t   = f1_score(y_te_tt, y_pred_tuned, zero_division=0)
    prec_t = precision_score(y_te_tt, y_pred_tuned, zero_division=0)
    rec_t  = recall_score(y_te_tt, y_pred_tuned, zero_division=0)
    spec_t = tn_t / (tn_t + fp_t)

    auc_t = roc_auc_score(y_te_tt, y_prob)
    ap_t  = average_precision_score(y_te_tt, y_prob)

    print("\nOPTIMAL THRESHOLD RESULTS:")
    print(f"  AUC={auc_t:.4f}  AP={ap_t:.4f}  "
          f"F1={f1_t:.4f}  Precision={prec_t:.4f}  "
          f"Sensitivity={rec_t:.4f}  Specificity={spec_t:.4f}")

    # ── IMPROVEMENT ─────────────────────────────
    print("\nIMPROVEMENT (Optimal - Default):")
    print(f"  ΔF1 = {f1_t - f1_d:.4f}")
    print(f"  ΔRecall = {rec_t - rec_d:.4f}")
    print(f"  ΔPrecision = {prec_t - prec_d:.4f}")

    print("\nClassification Report:")
    print(classification_report(y_te_tt, y_pred_tuned,
                                target_names=["No Recurrence", "Recurrence"]))

    # ── Confusion Matrices ─────────────────────────────
    fig, axes = plt.subplots(1, 2, figsize=(9, 4))

    ConfusionMatrixDisplay.from_predictions(
        y_te_tt, y_pred_default,
        display_labels=["No Recur.", "Recur."],
        ax=axes[0], colorbar=False)
    axes[0].set_title("Default τ = 0.50", fontweight="bold")

    ConfusionMatrixDisplay.from_predictions(
        y_te_tt, y_pred_tuned,
        display_labels=["No Recur.", "Recur."],
        ax=axes[1], colorbar=False)
    axes[1].set_title(f"Optimal τ = {best_t}", fontweight="bold")

    plt.suptitle(f"{model_name} — Threshold Tuning Effect",
                 fontsize=12, fontweight="bold")
    plt.tight_layout()
    plt.show()

    all_sweeps[model_name] = sweep

# =============================================================================
# FINAL SUMMARY — WITH THRESHOLD OPTIMISATION
# =============================================================================

# Combine baseline + extended results
all_results = baseline_results + extended_results
summary = pd.DataFrame(all_results)

# ── Format CV results (mean ± std (min, max)) ─────────────────────────────
for metric in ["Accuracy", "Roc_auc", "F1", "Precision",
               "Sensitivity", "Specificity"]:
    summary[f"CV {metric}"] = summary.apply(
        lambda row, m=metric: (
            f"{row[f'CV {m}_mean']:.3f} ± {row[f'CV {m}_std']:.3f} "
            f"(min={row[f'CV {m}_min']:.3f}, max={row[f'CV {m}_max']:.3f})"
        ), axis=1
    )

# Rename test metrics for clarity
summary.rename(columns={
    "Precision":   "Test Precision",
    "Sensitivity": "Test Sensitivity",
    "Specificity": "Test Specificity",
}, inplace=True)


# =============================================================================
# ADD THRESHOLD OPTIMISATION RESULTS
# =============================================================================

best_metrics = []

for model_name, sweep in all_sweeps.items():
    best_row = sweep.loc[sweep["F1"].idxmax()]

    best_metrics.append({
        "Model":             model_name,
        "Best Threshold":    round(best_row["Threshold"], 3),
        "F1 (Opt)":          round(best_row["F1"], 3),
        "Precision (Opt)":   round(best_row["Precision"], 3),
        "Sensitivity (Opt)": round(best_row["Sensitivity"], 3),
        "Specificity (Opt)": round(best_row["Specificity"], 3),
    })

best_df = pd.DataFrame(best_metrics)

# Merge threshold results with main table
summary = summary.merge(best_df, on="Model", how="left")


# =============================================================================
# FINAL DISPLAY TABLE
# =============================================================================

display_cols = [
    "Experiment", "Model",
    "CV Accuracy", "CV Roc_auc", "CV F1",
    "CV Precision", "CV Sensitivity", "CV Specificity",
    "Test Accuracy", "Test ROC-AUC", "Test F1",
    "Test Precision", "Test Sensitivity", "Test Specificity",
    "Best Threshold", "F1 (Opt)", "Precision (Opt)",
    "Sensitivity (Opt)", "Specificity (Opt)",
]

print("\n" + "=" * 120)
print("  FINAL RESULTS — CV (mean ± std (min, max)), Test, Threshold Optimisation")
print("=" * 120)

print(summary[display_cols].to_string(index=False))


# =============================================================================
# SAVE RESULTS
# =============================================================================

summary[display_cols].to_csv("results_with_thresholds.csv", index=False)
print("\n✅ Saved to results_with_thresholds.csv")


# ── Also save numeric-only version (for LaTeX tables) ───────────────────────
numeric_display = ["Experiment", "Model"]

for metric in ["Accuracy", "Roc_auc", "F1", "Precision",
               "Sensitivity", "Specificity"]:
    for stat in ["mean", "std", "min", "max"]:
        numeric_display.append(f"CV {metric}_{stat}")

numeric_display += [
    "Test Accuracy", "Test ROC-AUC", "Test F1",
    "Test Precision", "Test Sensitivity", "Test Specificity",
    "Best Threshold", "F1 (Opt)", "Precision (Opt)",
    "Sensitivity (Opt)", "Specificity (Opt)",
]

summary[numeric_display].to_csv("results_with_thresholds_numeric.csv", index=False)
print("✅ Saved to results_with_thresholds_numeric.csv")







