# -*- coding: utf-8 -*-
"""Experiment3_combined.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D1fGaEg6mw8o8C4JLSGnJeiA6SS-WBQD
"""

#!/usr/bin/env python3
"""
Breast Cancer Recurrence Prediction Pipeline
Combining Clinical Features (19) + Radiomics Features
For 2 Input Files Only
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score, roc_auc_score, f1_score, precision_score, recall_score,
    confusion_matrix, roc_curve, auc, precision_recall_curve
)

try:
    from xgboost import XGBClassifier
    HAS_XGBOOST = True
except ImportError:
    HAS_XGBOOST = False

from scipy import stats

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)
plt.style.use('seaborn-v0_8-darkgrid')


# ============================================================================
# STEP 1: LOAD 2 FILES
# ============================================================================

def load_two_files(file_clinical, file_radiomics):
    """
    Load your 2 input files.

    Args:
        file_clinical: Path to clinical features file (CSV or Excel)
        file_radiomics: Path to radiomics features file (CSV or Excel)

    Returns:
        clinical_df: Clinical features DataFrame
        radiomics_df: Radiomics features DataFrame
    """

    print("="*70)
    print("STEP 1: LOADING 2 FILES")
    print("="*70)

    # Load clinical file
    if file_clinical.endswith('.xlsx') or file_clinical.endswith('.xls'):
        clinical_df = pd.read_excel(file_clinical)
    else:
        clinical_df = pd.read_csv(file_clinical)

    print(f"\n✓ Clinical file loaded: {clinical_df.shape}")
    print(f"  Columns: {clinical_df.columns.tolist()}")

    # Load radiomics file
    if file_radiomics.endswith('.xlsx') or file_radiomics.endswith('.xls'):
        radiomics_df = pd.read_excel(file_radiomics)
    else:
        radiomics_df = pd.read_csv(file_radiomics)

    print(f"\n✓ Radiomics file loaded: {radiomics_df.shape}")
    print(f"  Columns: {radiomics_df.columns.tolist()}")

    return clinical_df, radiomics_df


# ============================================================================
# STEP 2: MERGE 2 FILES BY PATIENT_ID
# ============================================================================

def merge_two_files(clinical_df, radiomics_df, patient_id_col='patient_id'):
    """
    Merge clinical and radiomics files by patient_id.

    Args:
        clinical_df: Clinical features DataFrame
        radiomics_df: Radiomics features DataFrame
        patient_id_col: Column name for patient ID

    Returns:
        merged_df: Merged DataFrame
    """

    print("\n" + "="*70)
    print("STEP 2: MERGING FILES BY PATIENT_ID")
    print("="*70)

    print(f"\n✓ Clinical: {clinical_df.shape[0]} samples, {clinical_df.shape[1]} columns")
    print(f"✓ Radiomics: {radiomics_df.shape[0]} samples, {radiomics_df.shape[1]} columns")

    # Merge by patient_id (inner join)
    merged_df = clinical_df.merge(
        radiomics_df,
        on=patient_id_col,
        how='inner'
    )

    print(f"\n✓ After merge: {merged_df.shape[0]} samples, {merged_df.shape[1]} columns")
    print(f"✓ Total features (including patient_id): {merged_df.shape[1]}")
    print(f"✓ Total features (excluding patient_id): {merged_df.shape[1] - 1}")

    # Check for missing values
    missing_count = merged_df.isna().sum().sum()
    print(f"✓ Missing values in merged data: {missing_count}")

    return merged_df


# ============================================================================
# STEP 3: PREPARE FEATURES AND TARGET
# ============================================================================

def prepare_features_target(merged_df, target_col='recurrence_event_s', patient_id_col='patient_id'):
    """
    Separate features from target variable.

    Args:
        merged_df: Merged DataFrame
        target_col: Name of target column (recurrence yes/no)
        patient_id_col: Name of patient ID column

    Returns:
        X: Feature matrix
        y: Target variable
        patient_ids: Patient IDs
    """

    print("\n" + "="*70)
    print("STEP 3: PREPARING FEATURES AND TARGET")
    print("="*70)

    # Get patient IDs
    patient_ids = merged_df[patient_id_col].copy()

    # Get target
    y = merged_df[target_col].copy()
    print(f"\n✓ Target column: {target_col}")
    print(f"  Distribution: {y.value_counts().to_dict()}")

    # Get features (all except patient_id and target)
    X = merged_df.drop(columns=[patient_id_col, target_col])
    print(f"\n✓ Features: {X.shape[1]}")
    print(f"✓ Samples: {X.shape[0]}")

    # Handle missing values
    missing_per_feature = X.isna().sum()
    features_with_missing = missing_per_feature[missing_per_feature > 0]

    if len(features_with_missing) > 0:
        print(f"\n⚠️  Features with missing values:")
        print(features_with_missing)

        # Fill missing values with median
        X = X.fillna(X.median())
        print(f"\n✓ Missing values filled with median")
    else:
        print(f"\n✓ No missing values")

    return X, y, patient_ids


# ============================================================================
# STEP 4: TRAIN MODELS
# ============================================================================

def train_models(X_train, y_train, X_test, y_test):
    """
    Train three ML models.

    Args:
        X_train: Training features
        y_train: Training target
        X_test: Test features
        y_test: Test target

    Returns:
        trained_models: Dictionary of trained models
        predictions: Dictionary of predictions
    """

    print("\n" + "="*70)
    print("STEP 4: TRAINING MODELS")
    print("="*70)

    # Scale features
    print("\nScaling features...")
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    print("✓ Features scaled")

    # Define models
    models = {
        'Logistic Regression': LogisticRegression(
            max_iter=1000,
            class_weight='balanced',
            random_state=RANDOM_STATE
        ),
        'Random Forest': RandomForestClassifier(
            n_estimators=300,
            class_weight='balanced',
            random_state=RANDOM_STATE,
            n_jobs=-1
        ),
    }

    if HAS_XGBOOST:
        pos_weight = (y_train == 0).sum() / (y_train == 1).sum()
        models['XGBoost'] = XGBClassifier(
            n_estimators=300,
            eval_metric='logloss',
            random_state=RANDOM_STATE,
            scale_pos_weight=pos_weight,
            verbosity=0
        )

    trained_models = {}
    predictions = {}

    for model_name, model in models.items():
        print(f"\nTraining {model_name}...")
        model.fit(X_train_scaled, y_train)
        trained_models[model_name] = model

        y_pred = model.predict(X_test_scaled)
        y_proba = model.predict_proba(X_test_scaled)[:, 1]

        predictions[model_name] = {
            'y_pred': y_pred,
            'y_proba': y_proba,
            'y_test': y_test
        }

        print(f"✓ {model_name} trained")

    print(f"\n✅ TRAINING COMPLETE")

    return trained_models, predictions, scaler


# ============================================================================
# STEP 5: OPTIMIZE THRESHOLDS
# ============================================================================

def optimize_threshold(y_true, y_proba, model_name="Model"):
    """
    Find optimal threshold using F1-score maximization.

    Args:
        y_true: True labels
        y_proba: Predicted probabilities
        model_name: Model name for display

    Returns:
        optimal_threshold: Best threshold value
        metrics_df: DataFrame with all threshold metrics
    """

    thresholds = np.arange(0.05, 0.96, 0.05)
    results = []

    for t in thresholds:
        y_pred = (y_proba >= t).astype(int)

        tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()

        sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0
        specificity = tn / (tn + fp) if (tn + fp) > 0 else 0
        precision = tp / (tp + fp) if (tp + fp) > 0 else 0
        f1 = f1_score(y_true, y_pred, zero_division=0)
        accuracy = accuracy_score(y_true, y_pred)

        results.append({
            'Threshold': round(t, 2),
            'Sensitivity': sensitivity,
            'Specificity': specificity,
            'Precision': precision,
            'F1': f1,
            'Accuracy': accuracy,
        })

    metrics_df = pd.DataFrame(results)
    optimal_idx = metrics_df['F1'].idxmax()
    optimal_threshold = metrics_df.loc[optimal_idx, 'Threshold']

    print(f"{model_name}: τ* = {optimal_threshold:.2f} (F1 = {metrics_df.loc[optimal_idx, 'F1']:.4f})")

    return optimal_threshold, metrics_df


# ============================================================================
# STEP 6: EVALUATE MODELS
# ============================================================================

def evaluate_model(y_true, y_pred, y_proba, model_name):
    """
    Calculate comprehensive evaluation metrics.

    Args:
        y_true: True labels
        y_pred: Predicted labels (using optimal threshold)
        y_proba: Predicted probabilities
        model_name: Model name

    Returns:
        Dictionary with all metrics
    """

    accuracy = accuracy_score(y_true, y_pred)
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()

    sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    f1 = f1_score(y_true, y_pred, zero_division=0)
    roc_auc = roc_auc_score(y_true, y_proba)

    # Fisher's exact test p-value
    oddsratio, pvalue = stats.fisher_exact([[tp, fp], [fn, tn]])

    return {
        'Model': model_name,
        'Accuracy': accuracy,
        'Sensitivity': sensitivity,
        'Specificity': specificity,
        'Precision': precision,
        'F1-Score': f1,
        'ROC-AUC': roc_auc,
        'P-Value': pvalue
    }


def create_results_table(trained_models, predictions, optimal_thresholds):
    """
    Create final results summary table.

    Args:
        trained_models: Trained model objects
        predictions: Predictions dictionary
        optimal_thresholds: Optimal threshold per model

    Returns:
        results_df: Results DataFrame
    """

    results_list = []

    for model_name in trained_models.keys():
        if model_name not in predictions:
            continue

        preds = predictions[model_name]
        y_test = preds['y_test']
        y_proba = preds['y_proba']

        opt_threshold = optimal_thresholds.get(model_name, 0.5)
        y_pred = (y_proba >= opt_threshold).astype(int)

        metrics = evaluate_model(y_test, y_pred, y_proba, model_name)
        metrics['Optimal_Threshold'] = opt_threshold

        results_list.append(metrics)

    results_df = pd.DataFrame(results_list)

    col_order = ['Model', 'Optimal_Threshold', 'Accuracy', 'Sensitivity', 'Specificity',
                 'Precision', 'F1-Score', 'ROC-AUC', 'P-Value']
    results_df = results_df[[c for c in col_order if c in results_df.columns]]

    return results_df


# ============================================================================
# STEP 7: VISUALIZATIONS
# ============================================================================

def plot_roc_curves(predictions):
    """
    Plot ROC curves for all models.
    """

    fig, ax = plt.subplots(figsize=(10, 8))
    colors = {'Logistic Regression': '#1f77b4', 'Random Forest': '#ff7f0e', 'XGBoost': '#2ca02c'}

    for model_name, preds in predictions.items():
        y_test = preds['y_test']
        y_proba = preds['y_proba']

        fpr, tpr, _ = roc_curve(y_test, y_proba)
        roc_auc = auc(fpr, tpr)

        ax.plot(fpr, tpr, color=colors.get(model_name, '#000'), lw=2.5,
               label=f'{model_name} (AUC = {roc_auc:.3f})')

    ax.plot([0, 1], [0, 1], 'k--', lw=2, label='Random Classifier (AUC = 0.5)')

    ax.set_xlabel('False Positive Rate', fontsize=12, fontweight='bold')
    ax.set_ylabel('True Positive Rate', fontsize=12, fontweight='bold')
    ax.set_title('ROC Curves - Model Comparison', fontsize=14, fontweight='bold')
    ax.legend(fontsize=11, loc='lower right')
    ax.grid(alpha=0.3)
    ax.set_xlim([0.0, 1.0])
    ax.set_ylim([0.0, 1.05])

    plt.tight_layout()
    plt.savefig('roc_curves.png', dpi=300, bbox_inches='tight')
    plt.close()
    print("✓ Saved: roc_curves.png")


def plot_precision_recall_curves(predictions):
    """
    Plot Precision-Recall curves for all models.
    """

    fig, ax = plt.subplots(figsize=(10, 8))
    colors = {'Logistic Regression': '#1f77b4', 'Random Forest': '#ff7f0e', 'XGBoost': '#2ca02c'}

    for model_name, preds in predictions.items():
        y_test = preds['y_test']
        y_proba = preds['y_proba']

        precision, recall, _ = precision_recall_curve(y_test, y_proba)
        pr_auc = auc(recall, precision)

        ax.plot(recall, precision, color=colors.get(model_name, '#000'), lw=2.5,
               label=f'{model_name} (AP = {pr_auc:.3f})')

    ax.set_xlabel('Recall (Sensitivity)', fontsize=12, fontweight='bold')
    ax.set_ylabel('Precision', fontsize=12, fontweight='bold')
    ax.set_title('Precision-Recall Curves - Model Comparison', fontsize=14, fontweight='bold')
    ax.legend(fontsize=11, loc='upper right')
    ax.grid(alpha=0.3)
    ax.set_xlim([0.0, 1.0])
    ax.set_ylim([0.0, 1.05])

    plt.tight_layout()
    plt.savefig('precision_recall_curves.png', dpi=300, bbox_inches='tight')
    plt.close()
    print("✓ Saved: precision_recall_curves.png")


def plot_feature_importance(trained_models, feature_names):
    """
    Plot feature importance from tree-based models.
    """

    importance_dict = {}

    if 'Random Forest' in trained_models:
        rf_model = trained_models['Random Forest']
        rf_importance = pd.DataFrame({
            'Feature': feature_names,
            'Importance': rf_model.feature_importances_
        }).sort_values('Importance', ascending=False).head(15)
        importance_dict['Random Forest'] = rf_importance

    if 'XGBoost' in trained_models:
        xgb_model = trained_models['XGBoost']
        xgb_importance = pd.DataFrame({
            'Feature': feature_names,
            'Importance': xgb_model.feature_importances_
        }).sort_values('Importance', ascending=False).head(15)
        importance_dict['XGBoost'] = xgb_importance

    if not importance_dict:
        print("No tree-based models for feature importance.")
        return

    n_models = len(importance_dict)
    fig, axes = plt.subplots(1, n_models, figsize=(8*n_models, 6))

    if n_models == 1:
        axes = [axes]

    for ax, (model_name, importance_df) in zip(axes, importance_dict.items()):
        importance_df_sorted = importance_df.sort_values('Importance')
        ax.barh(importance_df_sorted['Feature'], importance_df_sorted['Importance'], color='steelblue')
        ax.set_xlabel('Importance', fontweight='bold')
        ax.set_title(f'{model_name}\nTop 15 Features', fontweight='bold', fontsize=12)
        ax.grid(axis='x', alpha=0.3)

    plt.tight_layout()
    plt.savefig('feature_importance.png', dpi=300, bbox_inches='tight')
    plt.close()
    print("✓ Saved: feature_importance.png")



# ============================================================================
# MAIN EXECUTION
# ============================================================================

if __name__ == "__main__":

    print("\n" + "#"*70)
    print("# BREAST CANCER RECURRENCE PREDICTION")
    print("# Clinical Features (19) + Radiomics Features")
    print("#"*70)

    # ========== STEP 1: UPDATE THESE PATHS ==========
    FILE_CLINICAL = "/content/drive/MyDrive/Project_Feb_26_Duke_Dataset/c.csv"
    FILE_RADIOMICS = "/content/drive/MyDrive/Project_Feb_26_Duke_Dataset/r.csv"
    # ================================================

    # STEP 1: Load files
    clinical_df, radiomics_df = load_two_files(FILE_CLINICAL, FILE_RADIOMICS)

    # STEP 2: Merge files
    merged_df = merge_two_files(clinical_df, radiomics_df)

    # STEP 3: Prepare features and target
    X, y, patient_ids = prepare_features_target(merged_df)

    # STEP 4: Split data
    print("\n" + "="*70)
    print("STEP 5: SPLITTING DATA (80/20)")
    print("="*70)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=RANDOM_STATE
    )

    print(f"\n✓ Training: {X_train.shape[0]} samples")
    print(f"✓ Testing: {X_test.shape[0]} samples")

    # STEP 5: Train models
    trained_models, predictions, scaler = train_models(X_train, y_train, X_test, y_test)

    # STEP 6: Optimize thresholds
    print("\n" + "="*70)
    print("STEP 6: OPTIMIZING THRESHOLDS")
    print("="*70)
    print()

    optimal_thresholds = {}
    for model_name, preds in predictions.items():
        opt_t, _ = optimize_threshold(preds['y_test'], preds['y_proba'], model_name)
        optimal_thresholds[model_name] = opt_t

    # STEP 7: Evaluate models
    print("\n" + "="*70)
    print("STEP 7: EVALUATING MODELS")
    print("="*70)

    results_df = create_results_table(trained_models, predictions, optimal_thresholds)

    print("\n" + "="*90)
    print("MODEL PERFORMANCE METRICS AT OPTIMAL THRESHOLDS")
    print("="*90)
    print(results_df.to_string(index=False))

    results_df.to_csv('model_results.csv', index=False)
    print("\n✓ Saved: model_results.csv")


    # ============================================================================
    # STEP 8: VISUALIZATIONS
    # ============================================================================

    print("\n" + "="*70)
    print("STEP 8: GENERATING VISUALIZATIONS")
    print("="*70)

    plot_roc_curves(predictions)
    plot_precision_recall_curves(predictions)
    plot_feature_importance(trained_models, X.columns)

    print("\n" + "="*90)
    print("✅ ANALYSIS COMPLETE")
    print("="*90)
    print("\nOutput files generated:")
    print("  - model_results.csv")
    print("  - roc_curves.png")
    print("  - precision_recall_curves.png")
    print("  - feature_importance.png")
    # ============================================================================
# STEP 9: FEATURE SELECTION (TOP FEATURES)
# ============================================================================

print("\n" + "="*70)
print("STEP 9: SELECTING TOP FEATURES")
print("="*70)

top_features = get_top_features(trained_models, X.columns, top_k=10)

X_selected = X[top_features]

print(f"\n✓ Reduced feature set: {X_selected.shape[1]} features")


# ============================================================================
# STEP 10: RETRAIN MODELS WITH SELECTED FEATURES
# ============================================================================

print("\n" + "="*70)
print("STEP 10: RETRAINING MODELS WITH SELECTED FEATURES")
print("="*70)

X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(
    X_selected, y, test_size=0.2, stratify=y, random_state=RANDOM_STATE
)

trained_models_s, predictions_s, scaler_s = train_models(
    X_train_s, y_train_s, X_test_s, y_test_s
)


# Optimize thresholds again
optimal_thresholds_s = {}

for model_name, preds in predictions_s.items():
    opt_t, _ = optimize_threshold(preds['y_test'], preds['y_proba'], model_name)
    optimal_thresholds_s[model_name] = opt_t


# Evaluate models
results_selected = create_results_table(
    trained_models_s,
    predictions_s,
    optimal_thresholds_s
)

print("\n" + "="*90)
print("MODEL PERFORMANCE (TOP FEATURES)")
print("="*90)
print(results_selected.to_string(index=False))

results_selected.to_csv("model_results_top_features.csv", index=False)

print("\n✓ Saved: model_results_top_features.csv")
# ============================================================================
# STEP 11: VISUALIZATIONS (SELECTED FEATURES)
# ============================================================================

print("\n" + "="*70)
print("STEP 11: GENERATING VISUALIZATIONS (TOP FEATURES)")
print("="*70)

plot_roc_curves(predictions_s)
plot_precision_recall_curves(predictions_s)
plot_feature_importance(trained_models_s, X_selected.columns)

# ============================================================================
# STEP 8: SELECT TOP FEATURES
# ============================================================================

def get_top_features(trained_models, feature_names, top_k=10):
    """
    Extract top features from each trained model.

    Args:
        trained_models: dictionary of trained models
        feature_names: list of feature names
        top_k: number of features per model

    Returns:
        selected_features: list of unique selected features
    """

    selected_features = set()

    # Logistic Regression
    if 'Logistic Regression' in trained_models:
        lr = trained_models['Logistic Regression']
        importance = np.abs(lr.coef_[0])

        lr_df = pd.DataFrame({
            "Feature": feature_names,
            "Importance": importance
        }).sort_values("Importance", ascending=False).head(top_k)

        selected_features.update(lr_df["Feature"].tolist())

    # Random Forest
    if 'Random Forest' in trained_models:
        rf = trained_models['Random Forest']

        rf_df = pd.DataFrame({
            "Feature": feature_names,
            "Importance": rf.feature_importances_
        }).sort_values("Importance", ascending=False).head(top_k)

        selected_features.update(rf_df["Feature"].tolist())

    # XGBoost
    if 'XGBoost' in trained_models:
        xgb = trained_models['XGBoost']

        xgb_df = pd.DataFrame({
            "Feature": feature_names,
            "Importance": xgb.feature_importances_
        }).sort_values("Importance", ascending=False).head(top_k)

        selected_features.update(xgb_df["Feature"].tolist())

    selected_features = list(selected_features)

    print("\n✓ Selected features:", len(selected_features))
    print(selected_features)

    return selected_features

