# -*- coding: utf-8 -*-
"""Radiomics_Featuress.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vjUxuKl2-4yvXEmS-4TMZiaQjDm4N9sM
"""

from google.colab import drive
drive.mount('/content/drive')

"""## 1. Import Libraries & Load Data"""

# ── (Colab only) Mount Google Drive ──────────────────────────────────────────
# from google.colab import drive
# drive.mount('/content/drive')

import psutil
import platform
import os
import warnings
import json

import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from scipy import stats

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    roc_auc_score, roc_curve,
    average_precision_score, precision_recall_curve,
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
)
from xgboost import XGBClassifier

warnings.filterwarnings('ignore')
np.random.seed(42)

# ── System info ───────────────────────────────────────────────────────────────
print("System    :", platform.system())
print("Processor :", platform.processor())
print("RAM (GB)  :", round(psutil.virtual_memory().total / 1e9, 2))
try:
    import torch
    print("GPU       :", torch.cuda.get_device_name(0))
except Exception:
    print("GPU       : Not available")

# ── Data paths — update as needed ────────────────────────────────────────────
CLINICAL_PATH = '/content/drive/MyDrive/Project_Feb_26_Duke_Dataset/selected_features_dataset.csv'
IMAGING_PATH  = '/content/drive/MyDrive/Project_Feb_26_Duke_Dataset/Imaging_Features.xlsx'

clinical = pd.read_csv(CLINICAL_PATH)
imaging  = pd.read_excel(IMAGING_PATH, sheet_name='Imaging Features')

print('Clinical data shape :', clinical.shape)
print('Imaging data shape  :', imaging.shape)
print('Missing recurrence  :', clinical['recurrence_event_s'].isna().sum())

"""## 2. Data Preparation"""

target = clinical[['recurrence_event_s']].copy()
target.columns = ['recurrence_event']

missing_indices = target[target['recurrence_event'].isna()].index.tolist()
print(f'Samples with missing recurrence values (indices): {missing_indices}')

valid_indices = target[target['recurrence_event'].notna()].index.tolist()
imaging_clean = imaging.loc[valid_indices].reset_index(drop=True)
target_clean  = target.loc[valid_indices].reset_index(drop=True)

print(f'\nSamples after removing missing targets : {len(imaging_clean)}')
print(f'Target distribution:\n{target_clean["recurrence_event"].value_counts()}')

radiomics   = imaging_clean.drop(columns=['patient_id']).copy()
patient_ids = imaging_clean['patient_id'].copy()

print(f'\nRadiomic features shape    : {radiomics.shape}')
print(f'Number of radiomic features: {radiomics.shape[1]}')

"""## 3. Handle Missing Values & Remove Constant Features"""

imputer           = SimpleImputer(strategy='median')
radiomics_imputed = pd.DataFrame(
    imputer.fit_transform(radiomics),
    columns=radiomics.columns
)
print('Missing values after imputation:', radiomics_imputed.isna().sum().sum())

feature_variances = radiomics_imputed.var()
constant_features = feature_variances[feature_variances == 0].index.tolist()
print(f'Constant features removed: {len(constant_features)}')

radiomics_clean = radiomics_imputed.drop(columns=constant_features)
print(f'Features after removing constants: {radiomics_clean.shape[1]}')

working_data = pd.concat([radiomics_clean, target_clean], axis=1)
print(f'Final working dataset shape: {working_data.shape}')

"""## 4. Feature Selection: Bootstrap AUC + 95% CI (Saha et al.)

> **Note**: This section implements the Saha et al. (2018) filter-based feature scoring.  
> - ✅ Bootstrap resampling — preserved exactly  
> - ✅ FIX applied: `roc_auc_score(y_boot, X_boot.ravel())` — resolves
"""

def calculate_auc_ci_bootstrap(X_series, y_series, n_bootstraps: int = 1000):
    """
    Calculate AUC with 95% CI using bootstrap resampling.
    Follows Saha et al. (2018) methodology.

    FIX: roc_auc_score receives X_boot.ravel() to avoid shape mismatch.

    Parameters
    ----------
    X_series     : pd.Series  — single radiomic feature
    y_series     : pd.Series  — binary recurrence label
    n_bootstraps : int        — number of bootstrap iterations

    Returns
    -------
    mean_auc, ci_lower, ci_upper : float
    """
    aucs = []
    n    = len(X_series)

    for _ in range(n_bootstraps):
        indices = np.random.choice(n, size=n, replace=True)
        X_boot  = X_series.iloc[indices].values.reshape(-1, 1)
        y_boot  = y_series.iloc[indices].values

        if len(np.unique(y_boot)) > 1:
            # ── FIX: .ravel() ensures 1-D array ──────────────────────────
            auc = roc_auc_score(y_boot, X_boot.ravel())
            aucs.append(auc)

    aucs     = np.array(aucs)
    mean_auc = np.mean(aucs)
    ci_lower = np.percentile(aucs, 2.5)
    ci_upper = np.percentile(aucs, 97.5)
    return mean_auc, ci_lower, ci_upper


feature_names = radiomics_clean.columns.tolist()
auc_results   = []

print('Calculating AUC + 95% CI for all features … (may take a few minutes)')
for i, feature in enumerate(feature_names):
    if (i + 1) % 100 == 0:
        print(f'  Processed {i + 1}/{len(feature_names)} features')

    mean_auc, ci_lower, ci_upper = calculate_auc_ci_bootstrap(
        radiomics_clean[feature],
        target_clean['recurrence_event'],
        n_bootstraps=1000
    )
    auc_results.append({
        'Feature'  : feature,
        'AUC'      : mean_auc,
        'CI_Lower' : ci_lower,
        'CI_Upper' : ci_upper,
        'CI_Width' : ci_upper - ci_lower,
    })

auc_df = (pd.DataFrame(auc_results)
          .sort_values('AUC', ascending=False)
          .reset_index(drop=True))

print('\nAUC calculation complete!')
print('\nTop 10 features by AUC:')
print(auc_df.head(10).to_string())

"""## 5. Correlation-Based Redundancy Removal

> **Note**: This is a **filter method** — independent of any model.  
> - ✅ Pearson correlation threshold = 0.8 — preserved exactly  
> - ✅ When |r| > threshold, feature with lower AUC is discarded  

"""

def select_non_redundant_features(
        radiomics_data: pd.DataFrame,
        auc_df: pd.DataFrame,
        correlation_threshold: float = 0.8,
        top_n: int = 30) -> list:
    """
    Select top non-redundant radiomic features using Pearson correlation.
    When |r| > threshold, the feature with the LOWER AUC is discarded.

    Parameters
    ----------
    radiomics_data        : pd.DataFrame — full radiomic feature matrix
    auc_df                : pd.DataFrame — AUC-ranked feature table
    correlation_threshold : float        — redundancy cutoff (default 0.8)
    top_n                 : int          — maximum features to return

    Returns
    -------
    selected_features : list[str]
    """
    selected_features = []
    feature_order     = auc_df['Feature'].tolist()
    corr_matrix       = radiomics_data[feature_order].corr().abs()

    for feature in feature_order:
        if len(selected_features) >= top_n:
            break

        is_redundant = False
        for sel_feat in selected_features:
            corr_val = corr_matrix.loc[feature, sel_feat]
            if corr_val > correlation_threshold:
                current_auc  = auc_df.loc[auc_df['Feature'] == feature,  'AUC'].values[0]
                selected_auc = auc_df.loc[auc_df['Feature'] == sel_feat, 'AUC'].values[0]
                if current_auc < selected_auc:
                    is_redundant = True
                    break

        if not is_redundant:
            selected_features.append(feature)

    return selected_features


# Pool of 30 non-redundant features — top-n subsets used in experiments below
filtered_features = select_non_redundant_features(
    radiomics_clean, auc_df,
    correlation_threshold=0.8, top_n=30
)

print(f'Filtered pool: {len(filtered_features)} non-redundant features')

selected_auc_df = (auc_df[auc_df['Feature'].isin(filtered_features)]
                   .sort_values('AUC', ascending=False)
                   .reset_index(drop=True))
print(selected_auc_df.to_string())

"""## 6. Forest Plot (Saha et al. Fig. 3 Style)"""

plot_data = (selected_auc_df.head(20)
             .sort_values('AUC', ascending=True)
             .reset_index(drop=True))

# 🔥 Wider figure
fig, ax = plt.subplots(figsize=(16, 10))   # ← كان 12,10

crosses_threshold = (plot_data['CI_Lower'] < 0.5) & (plot_data['CI_Upper'] > 0.5)
colors  = ['gray'   if c else 'black'  for c in crosses_threshold]
weights = ['normal' if c else 'bold'   for c in crosses_threshold]

for i, (_, row) in enumerate(plot_data.iterrows()):
    ax.errorbar(row['AUC'], i,
                xerr=[[row['AUC'] - row['CI_Lower']],
                      [row['CI_Upper'] - row['AUC']]],
                fmt='o', color=colors[i], ecolor=colors[i],
                markersize=8, linewidth=2.5, capsize=5)

    # 🔥 Move text slightly more left for clarity
    ax.text(0.39, i, row['Feature'], fontsize=10,
            weight=weights[i], ha='right', va='center')

# Reference line
ax.axvline(x=0.5, color='red', linestyle='--', linewidth=2,
           label='AUC = 0.5 (No discrimination)')

# 🔥 Extend x-axis slightly
ax.set_xlim(0.35, 1.0)

ax.set_ylim(-1, len(plot_data))

ax.set_xlabel('AUC (Area Under Curve)', fontsize=13, fontweight='bold')
ax.set_ylabel('Radiomic Features', fontsize=13, fontweight='bold')

ax.set_title('Forest Plot of Top 20 Radiomic Features\n(95% CI, Bootstrap Method)',
             fontsize=15, fontweight='bold', pad=20)

ax.set_yticks([])

ax.grid(axis='x', alpha=0.3)
ax.legend(fontsize=10, loc='lower right')

plt.tight_layout()

plt.savefig('forest_plot.png', dpi=300, bbox_inches='tight')
plt.show()

print('Forest plot saved → forest_plot.png')

"""## 7. Prepare Full Feature Matrix & Stratified Train / Test Split"""

y_all = target_clean['recurrence_event'].values.astype(int)

# Class-imbalance weight for XGBoost
n_pos            = np.sum(y_all == 1)
n_neg            = np.sum(y_all == 0)
scale_pos_weight = n_neg / n_pos

print(f'Positive cases (recurrence) : {n_pos}')
print(f'Negative cases              : {n_neg}')
print(f'scale_pos_weight (XGBoost)  : {scale_pos_weight:.4f}')

# 80 / 20 stratified split
X_full = radiomics_clean[filtered_features].copy()

X_train_raw, X_test_raw, y_train, y_test = train_test_split(
    X_full, y_all, test_size=0.20, random_state=42, stratify=y_all
)

# StandardScaler fitted ONLY on training data
scaler     = StandardScaler()
X_train_sc = pd.DataFrame(scaler.fit_transform(X_train_raw), columns=X_full.columns)
X_test_sc  = pd.DataFrame(scaler.transform(X_test_raw),      columns=X_full.columns)

print(f'\nTrain set : {X_train_sc.shape}  — class dist {np.bincount(y_train)}')
print(f'Test set  : {X_test_sc.shape}   — class dist {np.bincount(y_test)}')

"""## 8. Helper Functions"""

def compute_specificity(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    """Specificity = TN / (TN + FP) derived from confusion matrix."""
    cm = confusion_matrix(y_true, y_pred)
    if cm.shape == (2, 2):
        tn, fp, _, _ = cm.ravel()
        return tn / (tn + fp) if (tn + fp) > 0 else 0.0
    return 0.0


def evaluate_fold(y_true: np.ndarray, y_proba: np.ndarray) -> dict:
    """
    Compute all seven metrics for a single CV fold or the final test set.

    Uses predict_proba outputs for AUC and AP; threshold 0.5 for the rest.

    Returns
    -------
    dict — keys: auc, ap, accuracy, precision, recall, specificity, f1
    """
    y_pred = (y_proba >= 0.5).astype(int)
    return {
        'auc'        : roc_auc_score(y_true, y_proba),
        'ap'         : average_precision_score(y_true, y_proba),
        'accuracy'   : accuracy_score(y_true, y_pred),
        'precision'  : precision_score(y_true, y_pred, zero_division=0),
        'recall'     : recall_score(y_true, y_pred, zero_division=0),
        'specificity': compute_specificity(y_true, y_pred),
        'f1'         : f1_score(y_true, y_pred, zero_division=0),
    }


def aggregate_fold_metrics(fold_metrics: list) -> dict:
    """
    Aggregate per-fold metric dicts into mean ± std (min, max, per_fold).

    Parameters
    ----------
    fold_metrics : list[dict]  — one dict per CV fold

    Returns
    -------
    agg : dict  — {metric: {mean, std, min, max, per_fold}}
    """
    metric_keys = fold_metrics[0].keys()
    agg = {}
    for key in metric_keys:
        vals = [fm[key] for fm in fold_metrics]
        agg[key] = {
            'mean'     : float(np.mean(vals)),
            'std'      : float(np.std(vals, ddof=1)),
            'min'      : float(np.min(vals)),
            'max'      : float(np.max(vals)),
            'per_fold' : vals,
        }
    return agg


def print_cv_summary(agg: dict, model_name: str, n_features: int) -> None:
    """IEEE-format CV result printout."""
    print(f'\n  [{model_name} | n_features={n_features}]')
    for metric, stats_d in agg.items():
        print(
            f'    {metric.upper():12s}: '
            f'{stats_d["mean"]:.3f} \u00b1 {stats_d["std"]:.3f} '
            f'(min={stats_d["min"]:.3f}, max={stats_d["max"]:.3f})'
        )


def get_models(scale_pos_weight: float) -> dict:
    """Return freshly instantiated classifiers."""
    return {
        'Logistic Regression': LogisticRegression(
            random_state=42, class_weight='balanced', max_iter=1000
        ),
        'Random Forest': RandomForestClassifier(
            n_estimators=300, random_state=42,
            class_weight='balanced', n_jobs=-1
        ),
        'XGBoost': XGBClassifier(
            n_estimators=300, eval_metric='logloss',
            random_state=42, scale_pos_weight=scale_pos_weight,
            verbosity=0, use_label_encoder=False
        ),
    }

print('Helper functions ready.')

"""## 9. Experiment Loop — n_features ∈ {10, 15, 20, 25}

For each value of `n_features`:
- Select the top-n features from the AUC-ranked filtered pool
- Run **5-Fold Stratified Cross-Validation** → record per-fold metrics
- Fit the final model on the full training set
- Evaluate on the held-out test set

Metrics computed: **AUC · AP · Accuracy · Precision · Recall (Sensitivity) · Specificity · F1**  
Statistics: **mean ± std (min, max)** — derived from the 5 CV folds only.
"""

N_FEATURES_LIST = [10, 15, 20, 25]
N_SPLITS        = 5

skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=42)

# Master results containers
all_results  = []                                      # flat rows for summary DataFrame
cv_details   = {}                                      # cv_details[n_feat][model] = agg
test_results = {}                                      # test_results[n_feat][model] = metrics

# Curve data for plotting
MODEL_COLORS = {
    'Logistic Regression': '#1f77b4',
    'Random Forest'      : '#ff7f0e',
    'XGBoost'            : '#2ca02c',
}
roc_data = {nf: {} for nf in N_FEATURES_LIST}
pr_data  = {nf: {} for nf in N_FEATURES_LIST}

print('=' * 80)
print('EXPERIMENT LOOP: n_features \u2208 {10, 15, 20, 25}')
print('=' * 80)

for n_feat in N_FEATURES_LIST:
    print(f'\n{"-"*70}')
    print(f'  n_features = {n_feat}')
    print(f'{"-"*70}')

    top_n_features = filtered_features[:n_feat]    # top-n from AUC-ranked pool
    X_tr = X_train_sc[top_n_features].values
    X_te = X_test_sc[top_n_features].values

    cv_details[n_feat]   = {}
    test_results[n_feat] = {}

    models = get_models(scale_pos_weight)

    for model_name, model in models.items():

        # ── 5-Fold Cross-Validation ───────────────────────────────────────
        fold_metrics_list = []

        for fold, (tr_idx, va_idx) in enumerate(skf.split(X_tr, y_train)):
            Xf_tr, Xf_va = X_tr[tr_idx], X_tr[va_idx]
            yf_tr, yf_va = y_train[tr_idx], y_train[va_idx]

            model.fit(Xf_tr, yf_tr)
            y_proba_va = model.predict_proba(Xf_va)[:, 1]
            fold_metrics_list.append(evaluate_fold(yf_va, y_proba_va))

        # Aggregate
        agg = aggregate_fold_metrics(fold_metrics_list)
        cv_details[n_feat][model_name] = agg
        print_cv_summary(agg, model_name, n_feat)

        # ── Fit on full train → Evaluate on test ─────────────────────────
        model.fit(X_tr, y_train)
        y_proba_test = model.predict_proba(X_te)[:, 1]
        test_met     = evaluate_fold(y_test, y_proba_test)
        test_results[n_feat][model_name] = test_met

        # ROC / PR curve data
        fpr, tpr, _         = roc_curve(y_test, y_proba_test)
        prec_c, rec_c, _    = precision_recall_curve(y_test, y_proba_test)
        roc_data[n_feat][model_name] = (fpr, tpr, test_met['auc'])
        pr_data [n_feat][model_name] = (rec_c, prec_c, test_met['ap'])

        print(f'\n    \u2514\u2500 Test-set metrics ({model_name} | n={n_feat})')
        for metric, val in test_met.items():
            print(f'      {metric.upper():12s}: {val:.4f}')

        # Flat summary row
        row = {'n_features': n_feat, 'Model': model_name}
        for metric, stats_d in agg.items():
            row[f'cv_{metric}_mean'] = round(stats_d['mean'], 4)
            row[f'cv_{metric}_std']  = round(stats_d['std'],  4)
            row[f'cv_{metric}_min']  = round(stats_d['min'],  4)
            row[f'cv_{metric}_max']  = round(stats_d['max'],  4)
        for metric, val in test_met.items():
            row[f'test_{metric}'] = round(val, 4)
        all_results.append(row)

summary_df = pd.DataFrame(all_results)

print('\n' + '=' * 80)
print('FINAL SUMMARY TABLE')
print('=' * 80)
print(summary_df.to_string(index=False))

print(auc_df.head(20))
print(selected_auc_df.head(20))

# =============================================================================
# THRESHOLD TUNING — CROSS-VALIDATED (CORRECT VERSION)
# =============================================================================

def compute_all_metrics(y_true, y_prob, threshold=0.5):
    y_pred = (y_prob >= threshold).astype(int)

    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()

    return {
        "auc": roc_auc_score(y_true, y_prob),
        "ap": average_precision_score(y_true, y_prob),
        "accuracy": accuracy_score(y_true, y_pred),
        "precision": precision_score(y_true, y_pred, zero_division=0),
        "recall": recall_score(y_true, y_pred, zero_division=0),
        "specificity": tn / (tn + fp) if (tn + fp) > 0 else 0,
        "f1": f1_score(y_true, y_pred, zero_division=0),
    }


def tune_threshold_full(y_true, y_prob):
    thresholds = np.arange(0.05, 0.61, 0.025)
    rows = []

    for t in thresholds:
        metrics = compute_all_metrics(y_true, y_prob, threshold=t)
        metrics["threshold"] = t
        rows.append(metrics)

    sweep = pd.DataFrame(rows)

    best_idx = sweep["f1"].idxmax()
    return sweep.loc[best_idx]


# =============================================================================
# MAIN LOOP (WITH CV THRESHOLD TUNING)
# =============================================================================

threshold_results = []

print("\n" + "="*80)
print("THRESHOLD TUNING — CROSS-VALIDATED (FINAL VERSION)")
print("="*80)

for n_feat in N_FEATURES_LIST:

    print(f"\n{'-'*70}")
    print(f"  n_features = {n_feat}")
    print(f"{'-'*70}")

    top_n_features = filtered_features[:n_feat]
    X_tr = X_train_sc[top_n_features].values

    models = get_models(scale_pos_weight)

    for model_name, model in models.items():

        print(f"\n--- {model_name} ---")

        fold_metrics_list = []

        for fold, (tr_idx, va_idx) in enumerate(skf.split(X_tr, y_train)):

            Xf_tr, Xf_va = X_tr[tr_idx], X_tr[va_idx]
            yf_tr, yf_va = y_train[tr_idx], y_train[va_idx]

            model.fit(Xf_tr, yf_tr)
            y_prob_va = model.predict_proba(Xf_va)[:, 1]

            best_row = tune_threshold_full(yf_va, y_prob_va)

            fold_metrics_list.append(best_row)

        # ── Aggregate like main table ─────────────────────────────
        fold_df = pd.DataFrame(fold_metrics_list)

        agg = {}
        for col in ["auc", "ap", "accuracy", "precision", "recall", "specificity", "f1"]:
            agg[col] = {
                "mean": fold_df[col].mean(),
                "std":  fold_df[col].std(),
                "min":  fold_df[col].min(),
                "max":  fold_df[col].max(),
            }

        # Best threshold (mean across folds)
        mean_threshold = fold_df["threshold"].mean()

        # ── Store results ─────────────────────────────────────────
        row = {
            "n_features": n_feat,
            "Model": model_name,
            "Best Threshold (mean)": round(mean_threshold, 3),
        }

        for metric, stats_d in agg.items():
            row[f"{metric}_mean"] = round(stats_d["mean"], 4)
            row[f"{metric}_std"]  = round(stats_d["std"],  4)
            row[f"{metric}_min"]  = round(stats_d["min"],  4)
            row[f"{metric}_max"]  = round(stats_d["max"],  4)

        threshold_results.append(row)

        print(f"Mean F1: {agg['f1']['mean']:.4f} ± {agg['f1']['std']:.4f}")
        print(f"Mean Threshold: {mean_threshold:.3f}")


# =============================================================================
# FINAL TABLE
# =============================================================================

threshold_cv_df = pd.DataFrame(threshold_results)

print("\n" + "="*80)
print("THRESHOLD RESULTS (CROSS-VALIDATED)")
print("="*80)
print(threshold_cv_df.to_string(index=False))

# =============================================================================
# THRESHOLD TUNING — FINAL (CV + MEAN ± STD)
# =============================================================================

def compute_all_metrics(y_true, y_prob, threshold=0.5):
    y_pred = (y_prob >= threshold).astype(int)

    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()

    return {
        "auc": roc_auc_score(y_true, y_prob),
        "ap": average_precision_score(y_true, y_prob),
        "accuracy": accuracy_score(y_true, y_pred),
        "precision": precision_score(y_true, y_pred, zero_division=0),
        "recall": recall_score(y_true, y_pred, zero_division=0),
        "specificity": tn / (tn + fp) if (tn + fp) > 0 else 0,
        "f1": f1_score(y_true, y_pred, zero_division=0),
    }


def tune_threshold_full(y_true, y_prob):
    thresholds = np.arange(0.05, 0.61, 0.025)
    rows = []

    for t in thresholds:
        metrics = compute_all_metrics(y_true, y_prob, threshold=t)
        metrics["threshold"] = t
        rows.append(metrics)

    sweep = pd.DataFrame(rows)

    best_idx = sweep["f1"].idxmax()
    return sweep.loc[best_idx]


# =============================================================================
# MAIN LOOP
# =============================================================================

threshold_results = []

print("\n" + "="*80)
print("THRESHOLD TUNING — CROSS-VALIDATED (FINAL)")
print("="*80)

for n_feat in N_FEATURES_LIST:

    print(f"\n{'-'*70}")
    print(f"  n_features = {n_feat}")
    print(f"{'-'*70}")

    top_n_features = filtered_features[:n_feat]
    X_tr = X_train_sc[top_n_features].values

    models = get_models(scale_pos_weight)

    for model_name, model in models.items():

        print(f"\n--- {model_name} ---")

        fold_metrics_list = []

        for fold, (tr_idx, va_idx) in enumerate(skf.split(X_tr, y_train)):

            Xf_tr, Xf_va = X_tr[tr_idx], X_tr[va_idx]
            yf_tr, yf_va = y_train[tr_idx], y_train[va_idx]

            model.fit(Xf_tr, yf_tr)
            y_prob_va = model.predict_proba(Xf_va)[:, 1]

            best_row = tune_threshold_full(yf_va, y_prob_va)

            fold_metrics_list.append(best_row)

        fold_df = pd.DataFrame(fold_metrics_list)

        # ── Aggregate ─────────────────────────────────────────
        agg = {}
        for col in ["auc", "ap", "accuracy", "precision", "recall", "specificity", "f1"]:
            agg[col] = {
                "mean": fold_df[col].mean(),
                "std":  fold_df[col].std(),
                "min":  fold_df[col].min(),
                "max":  fold_df[col].max(),
            }

        mean_threshold = fold_df["threshold"].mean()

        # ── Final row (mean ± std format) ─────────────────────
        row = {
            "n_features": n_feat,
            "Model": model_name,
            "Best Threshold": round(mean_threshold, 3),
        }

        for metric, stats_d in agg.items():
            row[metric.upper()] = f"{stats_d['mean']:.4f} ± {stats_d['std']:.4f}"

        # OPTIONAL (لو بدك Excel detailed)
        for metric, stats_d in agg.items():
            row[f"{metric}_mean"] = round(stats_d["mean"], 4)
            row[f"{metric}_std"]  = round(stats_d["std"],  4)
            row[f"{metric}_min"]  = round(stats_d["min"],  4)
            row[f"{metric}_max"]  = round(stats_d["max"],  4)

        threshold_results.append(row)

        print(f"Mean F1: {agg['f1']['mean']:.4f} ± {agg['f1']['std']:.4f}")
        print(f"Mean Threshold: {mean_threshold:.3f}")


# =============================================================================
# FINAL TABLE
# =============================================================================

threshold_cv_df = pd.DataFrame(threshold_results)

print("\n" + "="*80)
print("THRESHOLD RESULTS (FINAL — MEAN ± STD)")
print("="*80)
print(threshold_cv_df.to_string(index=False))

"""## 10. Plots"""

for n_feat in N_FEATURES_LIST:
    fig, ax = plt.subplots(figsize=(8, 6))

    for model_name, (fpr, tpr, auc_val) in roc_data[n_feat].items():

        ax.plot(fpr, tpr,
                color=MODEL_COLORS[model_name], lw=2.5,
                label=f'{model_name} (AUC = {auc_val:.3f})')

        # ===== إضافة نقطة threshold optimal =====
        best_t = threshold_df[
            (threshold_df["n_features"] == n_feat) &
            (threshold_df["Model"] == model_name)
        ]["Best Threshold"].values[0]

        # احسب النقطة
        y_prob = None  # سنعيد حسابها
        model = get_models(scale_pos_weight)[model_name]

        top_n_features = filtered_features[:n_feat]
        X_tr = X_train_sc[top_n_features].values
        X_te = X_test_sc[top_n_features].values

        model.fit(X_tr, y_train)
        y_prob = model.predict_proba(X_te)[:, 1]

        fpr_t, tpr_t, thresholds = roc_curve(y_test, y_prob)

        # أقرب threshold
        idx = np.argmin(np.abs(thresholds - best_t))

        ax.scatter(fpr_t[idx], tpr_t[idx],
                   color=MODEL_COLORS[model_name],
                   s=80, edgecolor='black',
                   label=f'{model_name} (τ={best_t:.2f})')

    ax.plot([0, 1], [0, 1], 'k--', lw=2, label='Random Classifier (AUC = 0.50)')
    ax.set_xlabel('False Positive Rate', fontsize=12, fontweight='bold')
    ax.set_ylabel('True Positive Rate', fontsize=12, fontweight='bold')
    ax.set_title(f'ROC Curves — {n_feat} Features', fontsize=14, fontweight='bold')
    ax.legend(fontsize=9, loc='lower right')
    ax.grid(alpha=0.3)
    ax.set_xlim([0.0, 1.0])
    ax.set_ylim([0.0, 1.05])

    plt.tight_layout()
    plt.savefig(f'roc_curves_n{n_feat}.png', dpi=300, bbox_inches='tight')
    plt.show()

# ── Precision-Recall Curves — with Optimal Threshold Point ──────────────────────
for n_feat in N_FEATURES_LIST:
    fig, ax = plt.subplots(figsize=(8, 6))

    for model_name, (rec_c, prec_c, ap_val) in pr_data[n_feat].items():

        ax.plot(rec_c, prec_c,
                color=MODEL_COLORS[model_name], lw=2.5,
                label=f'{model_name} (AP = {ap_val:.3f})')

        # ===== إضافة نقطة threshold optimal =====
        best_t = threshold_df[
            (threshold_df["n_features"] == n_feat) &
            (threshold_df["Model"] == model_name)
        ]["Best Threshold"].values[0]

        # إعادة حساب probabilities
        model = get_models(scale_pos_weight)[model_name]

        top_n_features = filtered_features[:n_feat]
        X_tr = X_train_sc[top_n_features].values
        X_te = X_test_sc[top_n_features].values

        model.fit(X_tr, y_train)
        y_prob = model.predict_proba(X_te)[:, 1]

        # حساب PR curve
        precision, recall, thresholds = precision_recall_curve(y_test, y_prob)

        # ⚠️ ملاحظة: thresholds طولها أقل بـ 1 من precision/recall
        # لذلك نبحث عن أقرب threshold
        idx = np.argmin(np.abs(thresholds - best_t))

        ax.scatter(recall[idx], precision[idx],
                   color=MODEL_COLORS[model_name],
                   s=80, edgecolor='black',
                   label=f'{model_name} (τ={best_t:.2f})')

    # baseline (prevalence)
    baseline = y_test.mean()
    ax.axhline(y=baseline, color='gray', linestyle='--', lw=1.5,
               label=f'Baseline (prevalence = {baseline:.2f})')

    ax.set_xlabel('Recall', fontsize=12, fontweight='bold')
    ax.set_ylabel('Precision', fontsize=12, fontweight='bold')
    ax.set_title(f'Precision-Recall Curves — {n_feat} Features',
                 fontsize=14, fontweight='bold')

    ax.legend(fontsize=9, loc='upper right')
    ax.grid(alpha=0.3)
    ax.set_xlim([0.0, 1.0])
    ax.set_ylim([0.0, 1.05])

    plt.tight_layout()
    plt.savefig(f'pr_curves_n{n_feat}.png', dpi=300, bbox_inches='tight')
    plt.show()

    print(f'Saved pr_curves_n{n_feat}.png')

# ── AUC + AP bar charts vs n_features ────────────────────────────────────────
x      = np.arange(len(N_FEATURES_LIST))
bar_w  = 0.22
offset_vals = np.linspace(-bar_w, bar_w, len(MODEL_COLORS))

for metric_key, ylabel, title, fname in [
        ('auc', 'Mean CV AUC',               'Cross-Validated AUC vs. Number of Features',
         'auc_vs_nfeatures.png'),
        ('ap',  'Mean CV Average Precision',  'Cross-Validated AP vs. Number of Features',
         'ap_vs_nfeatures.png'),
]:
    fig, ax = plt.subplots(figsize=(9, 5))
    for offset, (model_name, color) in zip(offset_vals, MODEL_COLORS.items()):
        means = [cv_details[nf][model_name][metric_key]['mean'] for nf in N_FEATURES_LIST]
        stds  = [cv_details[nf][model_name][metric_key]['std']  for nf in N_FEATURES_LIST]
        ax.bar(x + offset, means, bar_w, yerr=stds,
               label=model_name, color=color, capsize=5,
               error_kw={'linewidth': 1.5})
    ax.set_xlabel('Number of Features', fontsize=12, fontweight='bold')
    ax.set_ylabel(ylabel,               fontsize=12, fontweight='bold')
    ax.set_title(title, fontsize=13, fontweight='bold')
    ax.set_xticks(x)
    ax.set_xticklabels([str(nf) for nf in N_FEATURES_LIST])
    ax.set_ylim(0, 1.05)
    ax.legend(fontsize=10)
    ax.grid(axis='y', alpha=0.3)
    plt.tight_layout()
    plt.savefig(fname, dpi=300, bbox_inches='tight')
    plt.show()
    print(f'Saved {fname}')

"""## 11. Feature Importance Analysis (Random Forest, n=20)"""

# =============================================================================
# FEATURE IMPORTANCE (n = 20 + Optimal Threshold context)
# =============================================================================

BEST_N = 20   # 🔥 اختيارك النهائي

print(f"\nUsing n_features = {BEST_N} for Feature Importance")

top_feats = filtered_features[:BEST_N]

X_tr_sel = X_train_sc[top_feats].values
X_te_sel = X_test_sc[top_feats].values

# نفس الموديل
rf_imp = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    class_weight='balanced',
    n_jobs=-1
)

rf_imp.fit(X_tr_sel, y_train)

# ── Feature Importance
feat_imp_df = (pd.DataFrame({
    'Feature': top_feats,
    'Importance': rf_imp.feature_importances_
})
.sort_values('Importance', ascending=False)
.reset_index(drop=True))

print('\nRandom Forest Feature Importances (Top 10):')
print(feat_imp_df.head(10).to_string(index=False))


# =============================================================================
# 🔥 APPLY OPTIMAL THRESHOLD (for interpretation)
# =============================================================================

# نجيب أفضل threshold لـ (RF, n=20)
best_row = threshold_df[
    (threshold_df["Model"] == "Random Forest") &
    (threshold_df["n_features"] == BEST_N)
].iloc[0]

best_threshold = best_row["Best Threshold"]

print(f"\nUsing optimal threshold = {best_threshold} for interpretation")

# predictions
y_prob = rf_imp.predict_proba(X_te_sel)[:, 1]
y_pred_opt = (y_prob >= best_threshold).astype(int)

from sklearn.metrics import classification_report

print("\nClassification Report (Optimal Threshold):")
print(classification_report(y_test, y_pred_opt, zero_division=0))


# =============================================================================
# Plot
# =============================================================================
fig, ax = plt.subplots(figsize=(12, 7))

ax.barh(range(len(feat_imp_df)),
        feat_imp_df['Importance'].values,
        color='steelblue',
        edgecolor='black')

ax.set_yticks(range(len(feat_imp_df)))
ax.set_yticklabels(feat_imp_df['Feature'].values, fontsize=9)

ax.set_xlabel('Importance Score', fontsize=11, fontweight='bold')

# 🔥 عنوان ذكي يعكس الحقيقة
ax.set_title(f'Random Forest Feature Importances (n=20)\nEvaluated with Optimal Threshold = {best_threshold}',
             fontsize=13, fontweight='bold')

ax.invert_yaxis()

# Highlight top 5
for i in range(5):
    ax.get_yticklabels()[i].set_fontweight('bold')

plt.tight_layout()
plt.savefig('feature_importance_n20_optimal_threshold.png', dpi=300, bbox_inches='tight')
plt.show()

print('Saved feature_importance_n20_optimal_threshold.png')

"""## 12. Export Results & Final Summary"""

# =============================================================================
# EXPORT RESULTS (FINAL VERSION — WITH THRESHOLD)
# =============================================================================

OUTPUT_FILE = "Radiomics_Recurrence_Prediction_CV_Threshold_Results.xlsx"

with pd.ExcelWriter(OUTPUT_FILE, engine='openpyxl') as writer:

    # ── 1. Filtered features
    selected_auc_df.to_excel(writer, sheet_name='Filtered_Features_Pool', index=False)

    # ── 2. Full summary
    summary_df.to_excel(writer, sheet_name='Full_Summary', index=False)

    # ── 3. All features AUC
    auc_df.to_excel(writer, sheet_name='All_Features_AUC', index=False)

    # ── 4. CV details
    cv_rows = []
    for n_feat in N_FEATURES_LIST:
        for model_name in MODEL_COLORS.keys():
            for metric, stats_d in cv_details[n_feat][model_name].items():
                cv_rows.append({
                    'n_features': n_feat,
                    'Model'     : model_name,
                    'Metric'    : metric.upper(),
                    'Mean'      : round(stats_d['mean'], 4),
                    'Std'       : round(stats_d['std'],  4),
                    'Min'       : round(stats_d['min'],  4),
                    'Max'       : round(stats_d['max'],  4),
                    'Fold_1'    : round(stats_d['per_fold'][0], 4),
                    'Fold_2'    : round(stats_d['per_fold'][1], 4),
                    'Fold_3'    : round(stats_d['per_fold'][2], 4),
                    'Fold_4'    : round(stats_d['per_fold'][3], 4),
                    'Fold_5'    : round(stats_d['per_fold'][4], 4),
                })

    pd.DataFrame(cv_rows).to_excel(writer, sheet_name='CV_Detail', index=False)

    # ── 5. Threshold results
    threshold_df.to_excel(writer, sheet_name='Threshold_Results', index=False)


print(f'Results exported → {OUTPUT_FILE}')

print(radiomics_clean.describe().head())

with pd.ExcelWriter('Breast_Cancer_Recurrence_Results.xlsx',
                    engine='openpyxl') as writer:

    selected_auc_df.to_excel(writer, sheet_name='Filtered_Features_Pool', index=False)
    summary_df.to_excel(writer, sheet_name='Full_Summary', index=False)
    auc_df.to_excel(writer, sheet_name='All_Features_AUC', index=False)

    cv_rows = []
    for n_feat in N_FEATURES_LIST:
        for model_name in MODEL_COLORS.keys():
            for metric, stats_d in cv_details[n_feat][model_name].items():
                cv_rows.append({
                    'n_features': n_feat,
                    'Model'     : model_name,
                    'Metric'    : metric.upper(),
                    'Mean'      : round(stats_d['mean'], 4),
                    'Std'       : round(stats_d['std'],  4),
                    'Min'       : round(stats_d['min'],  4),
                    'Max'       : round(stats_d['max'],  4),
                    'Fold_1'    : round(stats_d['per_fold'][0], 4),
                    'Fold_2'    : round(stats_d['per_fold'][1], 4),
                    'Fold_3'    : round(stats_d['per_fold'][2], 4),
                    'Fold_4'    : round(stats_d['per_fold'][3], 4),
                    'Fold_5'    : round(stats_d['per_fold'][4], 4),
                })
    pd.DataFrame(cv_rows).to_excel(writer, sheet_name='CV_Detail', index=False)

print('Results exported \u2192 Breast_Cancer_Recurrence_Results.xlsx')

print('\n' + '=' * 80)
print('ANALYSIS SUMMARY')
print('=' * 80)
print(f'Total radiomic features          : {radiomics.shape[1]}')
print(f'After removing constants         : {radiomics_clean.shape[1]}')
print(f'Non-redundant filtered pool      : {len(filtered_features)}')
print(f'n_features experiments           : {N_FEATURES_LIST}')
print(f'\nSamples analyzed               : {len(working_data)}')
print(f'Recurrence cases (positive)      : {int((y_all == 1).sum())}')
print(f'Non-recurrence cases (negative)  : {int((y_all == 0).sum())}')
print(f'Train / Test split               : {len(y_train)} / {len(y_test)}')

best_auc, best_cfg = 0.0, ('', 0)
for n_feat in N_FEATURES_LIST:
    for model_name in MODEL_COLORS.keys():
        m = cv_details[n_feat][model_name]['auc']['mean']
        if m > best_auc:
            best_auc, best_cfg = m, (model_name, n_feat)

print(f'\nBest CV AUC                      : {best_auc:.4f}')
print(f'  \u2192 Model      : {best_cfg[0]}')
print(f'  \u2192 n_features : {best_cfg[1]}')